// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewDistributedLock creates a new instance of DistributedLock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDistributedLock(t interface {
	mock.TestingT
	Cleanup(func())
}) *DistributedLock {
	mock := &DistributedLock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DistributedLock is an autogenerated mock type for the DistributedLock type
type DistributedLock struct {
	mock.Mock
}

type DistributedLock_Expecter struct {
	mock *mock.Mock
}

func (_m *DistributedLock) EXPECT() *DistributedLock_Expecter {
	return &DistributedLock_Expecter{mock: &_m.Mock}
}

// Lock provides a mock function for the type DistributedLock
func (_mock *DistributedLock) Lock(ctx context.Context) (context.Context, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Lock")
	}

	var r0 context.Context
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (context.Context, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) context.Context); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DistributedLock_Lock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lock'
type DistributedLock_Lock_Call struct {
	*mock.Call
}

// Lock is a helper method to define mock.On call
//   - ctx context.Context
func (_e *DistributedLock_Expecter) Lock(ctx any) *DistributedLock_Lock_Call {
	return &DistributedLock_Lock_Call{Call: _e.mock.On("Lock", ctx)}
}

func (_c *DistributedLock_Lock_Call) Run(run func(ctx context.Context)) *DistributedLock_Lock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DistributedLock_Lock_Call) Return(context1 context.Context, err error) *DistributedLock_Lock_Call {
	_c.Call.Return(context1, err)
	return _c
}

func (_c *DistributedLock_Lock_Call) RunAndReturn(run func(ctx context.Context) (context.Context, error)) *DistributedLock_Lock_Call {
	_c.Call.Return(run)
	return _c
}

// Unlock provides a mock function for the type DistributedLock
func (_mock *DistributedLock) Unlock(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Unlock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DistributedLock_Unlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unlock'
type DistributedLock_Unlock_Call struct {
	*mock.Call
}

// Unlock is a helper method to define mock.On call
//   - ctx context.Context
func (_e *DistributedLock_Expecter) Unlock(ctx any) *DistributedLock_Unlock_Call {
	return &DistributedLock_Unlock_Call{Call: _e.mock.On("Unlock", ctx)}
}

func (_c *DistributedLock_Unlock_Call) Run(run func(ctx context.Context)) *DistributedLock_Unlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DistributedLock_Unlock_Call) Return(err error) *DistributedLock_Unlock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DistributedLock_Unlock_Call) RunAndReturn(run func(ctx context.Context) error) *DistributedLock_Unlock_Call {
	_c.Call.Return(run)
	return _c
}
