// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	types0 "github.com/projecteru2/core/engine/types"
	types1 "github.com/projecteru2/core/resource/plugins/types"
	"github.com/projecteru2/core/resource/types"
	types2 "github.com/projecteru2/core/types"
	mock "github.com/stretchr/testify/mock"
)

// NewManager creates a new instance of Manager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *Manager {
	mock := &Manager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

type Manager_Expecter struct {
	mock *mock.Mock
}

func (_m *Manager) EXPECT() *Manager_Expecter {
	return &Manager_Expecter{mock: &_m.Mock}
}

// AddNode provides a mock function for the type Manager
func (_mock *Manager) AddNode(context1 context.Context, s string, resources types.Resources, info *types0.Info) (types.Resources, error) {
	ret := _mock.Called(context1, s, resources, info)

	if len(ret) == 0 {
		panic("no return value specified for AddNode")
	}

	var r0 types.Resources
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.Resources, *types0.Info) (types.Resources, error)); ok {
		return returnFunc(context1, s, resources, info)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.Resources, *types0.Info) types.Resources); ok {
		r0 = returnFunc(context1, s, resources, info)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.Resources)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, types.Resources, *types0.Info) error); ok {
		r1 = returnFunc(context1, s, resources, info)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Manager_AddNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddNode'
type Manager_AddNode_Call struct {
	*mock.Call
}

// AddNode is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - resources types.Resources
//   - info *types0.Info
func (_e *Manager_Expecter) AddNode(context1 any, s any, resources any, info any) *Manager_AddNode_Call {
	return &Manager_AddNode_Call{Call: _e.mock.On("AddNode", context1, s, resources, info)}
}

func (_c *Manager_AddNode_Call) Run(run func(context1 context.Context, s string, resources types.Resources, info *types0.Info)) *Manager_AddNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 types.Resources
		if args[2] != nil {
			arg2 = args[2].(types.Resources)
		}
		var arg3 *types0.Info
		if args[3] != nil {
			arg3 = args[3].(*types0.Info)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Manager_AddNode_Call) Return(resources1 types.Resources, err error) *Manager_AddNode_Call {
	_c.Call.Return(resources1, err)
	return _c
}

func (_c *Manager_AddNode_Call) RunAndReturn(run func(context1 context.Context, s string, resources types.Resources, info *types0.Info) (types.Resources, error)) *Manager_AddNode_Call {
	_c.Call.Return(run)
	return _c
}

// Alloc provides a mock function for the type Manager
func (_mock *Manager) Alloc(context1 context.Context, s string, n int, resources types.Resources) ([]types.Resources, []types.Resources, error) {
	ret := _mock.Called(context1, s, n, resources)

	if len(ret) == 0 {
		panic("no return value specified for Alloc")
	}

	var r0 []types.Resources
	var r1 []types.Resources
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, types.Resources) ([]types.Resources, []types.Resources, error)); ok {
		return returnFunc(context1, s, n, resources)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, types.Resources) []types.Resources); ok {
		r0 = returnFunc(context1, s, n, resources)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Resources)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, types.Resources) []types.Resources); ok {
		r1 = returnFunc(context1, s, n, resources)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]types.Resources)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, int, types.Resources) error); ok {
		r2 = returnFunc(context1, s, n, resources)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Manager_Alloc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Alloc'
type Manager_Alloc_Call struct {
	*mock.Call
}

// Alloc is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - n int
//   - resources types.Resources
func (_e *Manager_Expecter) Alloc(context1 any, s any, n any, resources any) *Manager_Alloc_Call {
	return &Manager_Alloc_Call{Call: _e.mock.On("Alloc", context1, s, n, resources)}
}

func (_c *Manager_Alloc_Call) Run(run func(context1 context.Context, s string, n int, resources types.Resources)) *Manager_Alloc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 types.Resources
		if args[3] != nil {
			arg3 = args[3].(types.Resources)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Manager_Alloc_Call) Return(resourcess []types.Resources, resourcess1 []types.Resources, err error) *Manager_Alloc_Call {
	_c.Call.Return(resourcess, resourcess1, err)
	return _c
}

func (_c *Manager_Alloc_Call) RunAndReturn(run func(context1 context.Context, s string, n int, resources types.Resources) ([]types.Resources, []types.Resources, error)) *Manager_Alloc_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetricsDescription provides a mock function for the type Manager
func (_mock *Manager) GetMetricsDescription(context1 context.Context) ([]*types1.MetricsDescription, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for GetMetricsDescription")
	}

	var r0 []*types1.MetricsDescription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*types1.MetricsDescription, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*types1.MetricsDescription); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types1.MetricsDescription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Manager_GetMetricsDescription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetricsDescription'
type Manager_GetMetricsDescription_Call struct {
	*mock.Call
}

// GetMetricsDescription is a helper method to define mock.On call
//   - context1 context.Context
func (_e *Manager_Expecter) GetMetricsDescription(context1 any) *Manager_GetMetricsDescription_Call {
	return &Manager_GetMetricsDescription_Call{Call: _e.mock.On("GetMetricsDescription", context1)}
}

func (_c *Manager_GetMetricsDescription_Call) Run(run func(context1 context.Context)) *Manager_GetMetricsDescription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Manager_GetMetricsDescription_Call) Return(metricsDescriptions []*types1.MetricsDescription, err error) *Manager_GetMetricsDescription_Call {
	_c.Call.Return(metricsDescriptions, err)
	return _c
}

func (_c *Manager_GetMetricsDescription_Call) RunAndReturn(run func(context1 context.Context) ([]*types1.MetricsDescription, error)) *Manager_GetMetricsDescription_Call {
	_c.Call.Return(run)
	return _c
}

// GetMostIdleNode provides a mock function for the type Manager
func (_mock *Manager) GetMostIdleNode(context1 context.Context, strings []string) (string, error) {
	ret := _mock.Called(context1, strings)

	if len(ret) == 0 {
		panic("no return value specified for GetMostIdleNode")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) (string, error)); ok {
		return returnFunc(context1, strings)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) string); ok {
		r0 = returnFunc(context1, strings)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(context1, strings)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Manager_GetMostIdleNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMostIdleNode'
type Manager_GetMostIdleNode_Call struct {
	*mock.Call
}

// GetMostIdleNode is a helper method to define mock.On call
//   - context1 context.Context
//   - strings []string
func (_e *Manager_Expecter) GetMostIdleNode(context1 any, strings any) *Manager_GetMostIdleNode_Call {
	return &Manager_GetMostIdleNode_Call{Call: _e.mock.On("GetMostIdleNode", context1, strings)}
}

func (_c *Manager_GetMostIdleNode_Call) Run(run func(context1 context.Context, strings []string)) *Manager_GetMostIdleNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Manager_GetMostIdleNode_Call) Return(s string, err error) *Manager_GetMostIdleNode_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Manager_GetMostIdleNode_Call) RunAndReturn(run func(context1 context.Context, strings []string) (string, error)) *Manager_GetMostIdleNode_Call {
	_c.Call.Return(run)
	return _c
}

// GetNodeMetrics provides a mock function for the type Manager
func (_mock *Manager) GetNodeMetrics(context1 context.Context, node *types2.Node) ([]*types1.Metrics, error) {
	ret := _mock.Called(context1, node)

	if len(ret) == 0 {
		panic("no return value specified for GetNodeMetrics")
	}

	var r0 []*types1.Metrics
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types2.Node) ([]*types1.Metrics, error)); ok {
		return returnFunc(context1, node)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types2.Node) []*types1.Metrics); ok {
		r0 = returnFunc(context1, node)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types1.Metrics)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types2.Node) error); ok {
		r1 = returnFunc(context1, node)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Manager_GetNodeMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNodeMetrics'
type Manager_GetNodeMetrics_Call struct {
	*mock.Call
}

// GetNodeMetrics is a helper method to define mock.On call
//   - context1 context.Context
//   - node *types2.Node
func (_e *Manager_Expecter) GetNodeMetrics(context1 any, node any) *Manager_GetNodeMetrics_Call {
	return &Manager_GetNodeMetrics_Call{Call: _e.mock.On("GetNodeMetrics", context1, node)}
}

func (_c *Manager_GetNodeMetrics_Call) Run(run func(context1 context.Context, node *types2.Node)) *Manager_GetNodeMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types2.Node
		if args[1] != nil {
			arg1 = args[1].(*types2.Node)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Manager_GetNodeMetrics_Call) Return(metricss []*types1.Metrics, err error) *Manager_GetNodeMetrics_Call {
	_c.Call.Return(metricss, err)
	return _c
}

func (_c *Manager_GetNodeMetrics_Call) RunAndReturn(run func(context1 context.Context, node *types2.Node) ([]*types1.Metrics, error)) *Manager_GetNodeMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// GetNodeResourceInfo provides a mock function for the type Manager
func (_mock *Manager) GetNodeResourceInfo(context1 context.Context, s string, workloads []*types2.Workload, b bool) (types.Resources, types.Resources, []string, error) {
	ret := _mock.Called(context1, s, workloads, b)

	if len(ret) == 0 {
		panic("no return value specified for GetNodeResourceInfo")
	}

	var r0 types.Resources
	var r1 types.Resources
	var r2 []string
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []*types2.Workload, bool) (types.Resources, types.Resources, []string, error)); ok {
		return returnFunc(context1, s, workloads, b)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []*types2.Workload, bool) types.Resources); ok {
		r0 = returnFunc(context1, s, workloads, b)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.Resources)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []*types2.Workload, bool) types.Resources); ok {
		r1 = returnFunc(context1, s, workloads, b)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(types.Resources)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, []*types2.Workload, bool) []string); ok {
		r2 = returnFunc(context1, s, workloads, b)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).([]string)
		}
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context, string, []*types2.Workload, bool) error); ok {
		r3 = returnFunc(context1, s, workloads, b)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// Manager_GetNodeResourceInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNodeResourceInfo'
type Manager_GetNodeResourceInfo_Call struct {
	*mock.Call
}

// GetNodeResourceInfo is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - workloads []*types2.Workload
//   - b bool
func (_e *Manager_Expecter) GetNodeResourceInfo(context1 any, s any, workloads any, b any) *Manager_GetNodeResourceInfo_Call {
	return &Manager_GetNodeResourceInfo_Call{Call: _e.mock.On("GetNodeResourceInfo", context1, s, workloads, b)}
}

func (_c *Manager_GetNodeResourceInfo_Call) Run(run func(context1 context.Context, s string, workloads []*types2.Workload, b bool)) *Manager_GetNodeResourceInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []*types2.Workload
		if args[2] != nil {
			arg2 = args[2].([]*types2.Workload)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Manager_GetNodeResourceInfo_Call) Return(resources types.Resources, resources1 types.Resources, strings []string, err error) *Manager_GetNodeResourceInfo_Call {
	_c.Call.Return(resources, resources1, strings, err)
	return _c
}

func (_c *Manager_GetNodeResourceInfo_Call) RunAndReturn(run func(context1 context.Context, s string, workloads []*types2.Workload, b bool) (types.Resources, types.Resources, []string, error)) *Manager_GetNodeResourceInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetNodesDeployCapacity provides a mock function for the type Manager
func (_mock *Manager) GetNodesDeployCapacity(context1 context.Context, strings []string, resources types.Resources) (map[string]*types1.NodeDeployCapacity, int, error) {
	ret := _mock.Called(context1, strings, resources)

	if len(ret) == 0 {
		panic("no return value specified for GetNodesDeployCapacity")
	}

	var r0 map[string]*types1.NodeDeployCapacity
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, types.Resources) (map[string]*types1.NodeDeployCapacity, int, error)); ok {
		return returnFunc(context1, strings, resources)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, types.Resources) map[string]*types1.NodeDeployCapacity); ok {
		r0 = returnFunc(context1, strings, resources)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*types1.NodeDeployCapacity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, types.Resources) int); ok {
		r1 = returnFunc(context1, strings, resources)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, []string, types.Resources) error); ok {
		r2 = returnFunc(context1, strings, resources)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Manager_GetNodesDeployCapacity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNodesDeployCapacity'
type Manager_GetNodesDeployCapacity_Call struct {
	*mock.Call
}

// GetNodesDeployCapacity is a helper method to define mock.On call
//   - context1 context.Context
//   - strings []string
//   - resources types.Resources
func (_e *Manager_Expecter) GetNodesDeployCapacity(context1 any, strings any, resources any) *Manager_GetNodesDeployCapacity_Call {
	return &Manager_GetNodesDeployCapacity_Call{Call: _e.mock.On("GetNodesDeployCapacity", context1, strings, resources)}
}

func (_c *Manager_GetNodesDeployCapacity_Call) Run(run func(context1 context.Context, strings []string, resources types.Resources)) *Manager_GetNodesDeployCapacity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 types.Resources
		if args[2] != nil {
			arg2 = args[2].(types.Resources)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Manager_GetNodesDeployCapacity_Call) Return(stringToNodeDeployCapacity map[string]*types1.NodeDeployCapacity, n int, err error) *Manager_GetNodesDeployCapacity_Call {
	_c.Call.Return(stringToNodeDeployCapacity, n, err)
	return _c
}

func (_c *Manager_GetNodesDeployCapacity_Call) RunAndReturn(run func(context1 context.Context, strings []string, resources types.Resources) (map[string]*types1.NodeDeployCapacity, int, error)) *Manager_GetNodesDeployCapacity_Call {
	_c.Call.Return(run)
	return _c
}

// Realloc provides a mock function for the type Manager
func (_mock *Manager) Realloc(context1 context.Context, s string, resources types.Resources, resources1 types.Resources) (types.Resources, types.Resources, types.Resources, error) {
	ret := _mock.Called(context1, s, resources, resources1)

	if len(ret) == 0 {
		panic("no return value specified for Realloc")
	}

	var r0 types.Resources
	var r1 types.Resources
	var r2 types.Resources
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.Resources, types.Resources) (types.Resources, types.Resources, types.Resources, error)); ok {
		return returnFunc(context1, s, resources, resources1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.Resources, types.Resources) types.Resources); ok {
		r0 = returnFunc(context1, s, resources, resources1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.Resources)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, types.Resources, types.Resources) types.Resources); ok {
		r1 = returnFunc(context1, s, resources, resources1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(types.Resources)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, types.Resources, types.Resources) types.Resources); ok {
		r2 = returnFunc(context1, s, resources, resources1)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(types.Resources)
		}
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context, string, types.Resources, types.Resources) error); ok {
		r3 = returnFunc(context1, s, resources, resources1)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// Manager_Realloc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Realloc'
type Manager_Realloc_Call struct {
	*mock.Call
}

// Realloc is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - resources types.Resources
//   - resources1 types.Resources
func (_e *Manager_Expecter) Realloc(context1 any, s any, resources any, resources1 any) *Manager_Realloc_Call {
	return &Manager_Realloc_Call{Call: _e.mock.On("Realloc", context1, s, resources, resources1)}
}

func (_c *Manager_Realloc_Call) Run(run func(context1 context.Context, s string, resources types.Resources, resources1 types.Resources)) *Manager_Realloc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 types.Resources
		if args[2] != nil {
			arg2 = args[2].(types.Resources)
		}
		var arg3 types.Resources
		if args[3] != nil {
			arg3 = args[3].(types.Resources)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Manager_Realloc_Call) Return(resources2 types.Resources, resources3 types.Resources, resources4 types.Resources, err error) *Manager_Realloc_Call {
	_c.Call.Return(resources2, resources3, resources4, err)
	return _c
}

func (_c *Manager_Realloc_Call) RunAndReturn(run func(context1 context.Context, s string, resources types.Resources, resources1 types.Resources) (types.Resources, types.Resources, types.Resources, error)) *Manager_Realloc_Call {
	_c.Call.Return(run)
	return _c
}

// Remap provides a mock function for the type Manager
func (_mock *Manager) Remap(context1 context.Context, s string, workloads []*types2.Workload) (map[string]types.Resources, error) {
	ret := _mock.Called(context1, s, workloads)

	if len(ret) == 0 {
		panic("no return value specified for Remap")
	}

	var r0 map[string]types.Resources
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []*types2.Workload) (map[string]types.Resources, error)); ok {
		return returnFunc(context1, s, workloads)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []*types2.Workload) map[string]types.Resources); ok {
		r0 = returnFunc(context1, s, workloads)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]types.Resources)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []*types2.Workload) error); ok {
		r1 = returnFunc(context1, s, workloads)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Manager_Remap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remap'
type Manager_Remap_Call struct {
	*mock.Call
}

// Remap is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - workloads []*types2.Workload
func (_e *Manager_Expecter) Remap(context1 any, s any, workloads any) *Manager_Remap_Call {
	return &Manager_Remap_Call{Call: _e.mock.On("Remap", context1, s, workloads)}
}

func (_c *Manager_Remap_Call) Run(run func(context1 context.Context, s string, workloads []*types2.Workload)) *Manager_Remap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []*types2.Workload
		if args[2] != nil {
			arg2 = args[2].([]*types2.Workload)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Manager_Remap_Call) Return(stringToResources map[string]types.Resources, err error) *Manager_Remap_Call {
	_c.Call.Return(stringToResources, err)
	return _c
}

func (_c *Manager_Remap_Call) RunAndReturn(run func(context1 context.Context, s string, workloads []*types2.Workload) (map[string]types.Resources, error)) *Manager_Remap_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveNode provides a mock function for the type Manager
func (_mock *Manager) RemoveNode(context1 context.Context, s string) error {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for RemoveNode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Manager_RemoveNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveNode'
type Manager_RemoveNode_Call struct {
	*mock.Call
}

// RemoveNode is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *Manager_Expecter) RemoveNode(context1 any, s any) *Manager_RemoveNode_Call {
	return &Manager_RemoveNode_Call{Call: _e.mock.On("RemoveNode", context1, s)}
}

func (_c *Manager_RemoveNode_Call) Run(run func(context1 context.Context, s string)) *Manager_RemoveNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Manager_RemoveNode_Call) Return(err error) *Manager_RemoveNode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Manager_RemoveNode_Call) RunAndReturn(run func(context1 context.Context, s string) error) *Manager_RemoveNode_Call {
	_c.Call.Return(run)
	return _c
}

// RollbackAlloc provides a mock function for the type Manager
func (_mock *Manager) RollbackAlloc(context1 context.Context, s string, resourcess []types.Resources) error {
	ret := _mock.Called(context1, s, resourcess)

	if len(ret) == 0 {
		panic("no return value specified for RollbackAlloc")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []types.Resources) error); ok {
		r0 = returnFunc(context1, s, resourcess)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Manager_RollbackAlloc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RollbackAlloc'
type Manager_RollbackAlloc_Call struct {
	*mock.Call
}

// RollbackAlloc is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - resourcess []types.Resources
func (_e *Manager_Expecter) RollbackAlloc(context1 any, s any, resourcess any) *Manager_RollbackAlloc_Call {
	return &Manager_RollbackAlloc_Call{Call: _e.mock.On("RollbackAlloc", context1, s, resourcess)}
}

func (_c *Manager_RollbackAlloc_Call) Run(run func(context1 context.Context, s string, resourcess []types.Resources)) *Manager_RollbackAlloc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []types.Resources
		if args[2] != nil {
			arg2 = args[2].([]types.Resources)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Manager_RollbackAlloc_Call) Return(err error) *Manager_RollbackAlloc_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Manager_RollbackAlloc_Call) RunAndReturn(run func(context1 context.Context, s string, resourcess []types.Resources) error) *Manager_RollbackAlloc_Call {
	_c.Call.Return(run)
	return _c
}

// RollbackRealloc provides a mock function for the type Manager
func (_mock *Manager) RollbackRealloc(context1 context.Context, s string, resources types.Resources) error {
	ret := _mock.Called(context1, s, resources)

	if len(ret) == 0 {
		panic("no return value specified for RollbackRealloc")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.Resources) error); ok {
		r0 = returnFunc(context1, s, resources)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Manager_RollbackRealloc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RollbackRealloc'
type Manager_RollbackRealloc_Call struct {
	*mock.Call
}

// RollbackRealloc is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - resources types.Resources
func (_e *Manager_Expecter) RollbackRealloc(context1 any, s any, resources any) *Manager_RollbackRealloc_Call {
	return &Manager_RollbackRealloc_Call{Call: _e.mock.On("RollbackRealloc", context1, s, resources)}
}

func (_c *Manager_RollbackRealloc_Call) Run(run func(context1 context.Context, s string, resources types.Resources)) *Manager_RollbackRealloc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 types.Resources
		if args[2] != nil {
			arg2 = args[2].(types.Resources)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Manager_RollbackRealloc_Call) Return(err error) *Manager_RollbackRealloc_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Manager_RollbackRealloc_Call) RunAndReturn(run func(context1 context.Context, s string, resources types.Resources) error) *Manager_RollbackRealloc_Call {
	_c.Call.Return(run)
	return _c
}

// SetNodeResourceCapacity provides a mock function for the type Manager
func (_mock *Manager) SetNodeResourceCapacity(context1 context.Context, s string, resources types.Resources, resources1 types.Resources, b bool, b1 bool) (types.Resources, types.Resources, error) {
	ret := _mock.Called(context1, s, resources, resources1, b, b1)

	if len(ret) == 0 {
		panic("no return value specified for SetNodeResourceCapacity")
	}

	var r0 types.Resources
	var r1 types.Resources
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.Resources, types.Resources, bool, bool) (types.Resources, types.Resources, error)); ok {
		return returnFunc(context1, s, resources, resources1, b, b1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.Resources, types.Resources, bool, bool) types.Resources); ok {
		r0 = returnFunc(context1, s, resources, resources1, b, b1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.Resources)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, types.Resources, types.Resources, bool, bool) types.Resources); ok {
		r1 = returnFunc(context1, s, resources, resources1, b, b1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(types.Resources)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, types.Resources, types.Resources, bool, bool) error); ok {
		r2 = returnFunc(context1, s, resources, resources1, b, b1)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Manager_SetNodeResourceCapacity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNodeResourceCapacity'
type Manager_SetNodeResourceCapacity_Call struct {
	*mock.Call
}

// SetNodeResourceCapacity is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - resources types.Resources
//   - resources1 types.Resources
//   - b bool
//   - b1 bool
func (_e *Manager_Expecter) SetNodeResourceCapacity(context1 any, s any, resources any, resources1 any, b any, b1 any) *Manager_SetNodeResourceCapacity_Call {
	return &Manager_SetNodeResourceCapacity_Call{Call: _e.mock.On("SetNodeResourceCapacity", context1, s, resources, resources1, b, b1)}
}

func (_c *Manager_SetNodeResourceCapacity_Call) Run(run func(context1 context.Context, s string, resources types.Resources, resources1 types.Resources, b bool, b1 bool)) *Manager_SetNodeResourceCapacity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 types.Resources
		if args[2] != nil {
			arg2 = args[2].(types.Resources)
		}
		var arg3 types.Resources
		if args[3] != nil {
			arg3 = args[3].(types.Resources)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		var arg5 bool
		if args[5] != nil {
			arg5 = args[5].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *Manager_SetNodeResourceCapacity_Call) Return(resources2 types.Resources, resources3 types.Resources, err error) *Manager_SetNodeResourceCapacity_Call {
	_c.Call.Return(resources2, resources3, err)
	return _c
}

func (_c *Manager_SetNodeResourceCapacity_Call) RunAndReturn(run func(context1 context.Context, s string, resources types.Resources, resources1 types.Resources, b bool, b1 bool) (types.Resources, types.Resources, error)) *Manager_SetNodeResourceCapacity_Call {
	_c.Call.Return(run)
	return _c
}

// SetNodeResourceUsage provides a mock function for the type Manager
func (_mock *Manager) SetNodeResourceUsage(context1 context.Context, s string, resources types.Resources, resources1 types.Resources, resourcess []types.Resources, b bool, b1 bool) (types.Resources, types.Resources, error) {
	ret := _mock.Called(context1, s, resources, resources1, resourcess, b, b1)

	if len(ret) == 0 {
		panic("no return value specified for SetNodeResourceUsage")
	}

	var r0 types.Resources
	var r1 types.Resources
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.Resources, types.Resources, []types.Resources, bool, bool) (types.Resources, types.Resources, error)); ok {
		return returnFunc(context1, s, resources, resources1, resourcess, b, b1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.Resources, types.Resources, []types.Resources, bool, bool) types.Resources); ok {
		r0 = returnFunc(context1, s, resources, resources1, resourcess, b, b1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.Resources)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, types.Resources, types.Resources, []types.Resources, bool, bool) types.Resources); ok {
		r1 = returnFunc(context1, s, resources, resources1, resourcess, b, b1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(types.Resources)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, types.Resources, types.Resources, []types.Resources, bool, bool) error); ok {
		r2 = returnFunc(context1, s, resources, resources1, resourcess, b, b1)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Manager_SetNodeResourceUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNodeResourceUsage'
type Manager_SetNodeResourceUsage_Call struct {
	*mock.Call
}

// SetNodeResourceUsage is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - resources types.Resources
//   - resources1 types.Resources
//   - resourcess []types.Resources
//   - b bool
//   - b1 bool
func (_e *Manager_Expecter) SetNodeResourceUsage(context1 any, s any, resources any, resources1 any, resourcess any, b any, b1 any) *Manager_SetNodeResourceUsage_Call {
	return &Manager_SetNodeResourceUsage_Call{Call: _e.mock.On("SetNodeResourceUsage", context1, s, resources, resources1, resourcess, b, b1)}
}

func (_c *Manager_SetNodeResourceUsage_Call) Run(run func(context1 context.Context, s string, resources types.Resources, resources1 types.Resources, resourcess []types.Resources, b bool, b1 bool)) *Manager_SetNodeResourceUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 types.Resources
		if args[2] != nil {
			arg2 = args[2].(types.Resources)
		}
		var arg3 types.Resources
		if args[3] != nil {
			arg3 = args[3].(types.Resources)
		}
		var arg4 []types.Resources
		if args[4] != nil {
			arg4 = args[4].([]types.Resources)
		}
		var arg5 bool
		if args[5] != nil {
			arg5 = args[5].(bool)
		}
		var arg6 bool
		if args[6] != nil {
			arg6 = args[6].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *Manager_SetNodeResourceUsage_Call) Return(resources2 types.Resources, resources3 types.Resources, err error) *Manager_SetNodeResourceUsage_Call {
	_c.Call.Return(resources2, resources3, err)
	return _c
}

func (_c *Manager_SetNodeResourceUsage_Call) RunAndReturn(run func(context1 context.Context, s string, resources types.Resources, resources1 types.Resources, resourcess []types.Resources, b bool, b1 bool) (types.Resources, types.Resources, error)) *Manager_SetNodeResourceUsage_Call {
	_c.Call.Return(run)
	return _c
}
