#!/bin/bash

ROOT="`pwd`/build"
BIN="$ROOT/usr/bin"
CONF="$ROOT/etc/eru-core"
SERVICE="$ROOT/usr/lib/systemd/system"


mkdir -p $BIN
mkdir -p $CONF
mkdir -p $SERVICE

mv eru-core $BIN
mv core.yaml.sample $CONF
mv eru-core.service $SERVICE

VERSION=$(cat VERSION)
echo $VERSION rpm build begin

fpm -f -s dir -t rpm -n eru-core --epoch 0 -v $VERSION --iteration 1.el7 -C $ROOT -p $PWD --verbose --category 'Development/App' --description 'docker eru core' --url 'http://github.com/projecteru/eru-core' --license 'BSD'  --no-rpm-sign usr etc

rm -rf $ROOT
