#!/bin/bash

ROOT="`pwd`/build"
BIN="$ROOT/usr/bin"
CONF="$ROOT/etc/eru"
SERVICE="$ROOT/usr/lib/systemd/system"

mkdir -p $BIN
mkdir -p $CONF
mkdir -p $SERVICE

mv eru-core $BIN
mv core.yaml.sample $CONF
mv eru-core.service $SERVICE

VERSION=$(cat VERSION)
echo $VERSION rpm build begin

fpm -f -s dir -t rpm -n eru-core --epoch 0 -v $VERSION --iteration 1.el7 -C $ROOT -p $PWD --verbose --rpm-auto-add-directories --category 'Development/App' --description 'docker eru core' --url 'https://github.com/projecteru2/core' --license 'MIT'  --no-rpm-sign usr etc

rm -rf $ROOT
