appname: "eru"
entrypoints:
  core:
    cmd: "/usr/bin/eru-core --config /core.yaml"
    restart: always
    publish:
      - "5001"
    healthcheck:
      tcp_ports:
        - "5001"
stages:
  - build
  - pack
builds:
  build:
    base: "golang:alpine"
    # only support ssh protocol
    repo: "git@github.com:projecteru2/core.git"
    version: "HEAD"
    security: false
    dir: /go/src/github.com/projecteru2/core
    commands:
      - apk add --no-cache build-base musl-dev libgit2-dev git curl make
      - make test
      - make binary
    cache:
      /go/src/github.com/projecteru2/core/eru-core: /usr/bin/eru-core
  pack:
    base: alpine
    labels:
      ERU: 1
      core: 1
    envs:
      CORE_IN_DOCKER: 1
    commands:
      - apk add --no-cache libgit2
      - rm -rf /var/cache/apk/*

