// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Source is an autogenerated mock type for the Source type
type Source struct {
	mock.Mock
}

// Artifact provides a mock function with given fields: artifact, path
func (_m *Source) Artifact(artifact string, path string) error {
	ret := _m.Called(artifact, path)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(artifact, path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Security provides a mock function with given fields: path
func (_m *Source) Security(path string) error {
	ret := _m.Called(path)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SourceCode provides a mock function with given fields: repository, path, revision, submodule
func (_m *Source) SourceCode(repository string, path string, revision string, submodule bool) error {
	ret := _m.Called(repository, path, revision, submodule)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, bool) error); ok {
		r0 = rf(repository, path, revision, submodule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
