// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	types0 "github.com/projecteru2/core/engine/types"
	"github.com/projecteru2/core/types"
	mock "github.com/stretchr/testify/mock"
)

// NewCluster creates a new instance of Cluster. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCluster(t interface {
	mock.TestingT
	Cleanup(func())
}) *Cluster {
	mock := &Cluster{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Cluster is an autogenerated mock type for the Cluster type
type Cluster struct {
	mock.Mock
}

type Cluster_Expecter struct {
	mock *mock.Mock
}

func (_m *Cluster) EXPECT() *Cluster_Expecter {
	return &Cluster_Expecter{mock: &_m.Mock}
}

// AddNode provides a mock function for the type Cluster
func (_mock *Cluster) AddNode(context1 context.Context, addNodeOptions *types.AddNodeOptions) (*types.Node, error) {
	ret := _mock.Called(context1, addNodeOptions)

	if len(ret) == 0 {
		panic("no return value specified for AddNode")
	}

	var r0 *types.Node
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.AddNodeOptions) (*types.Node, error)); ok {
		return returnFunc(context1, addNodeOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.AddNodeOptions) *types.Node); ok {
		r0 = returnFunc(context1, addNodeOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Node)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types.AddNodeOptions) error); ok {
		r1 = returnFunc(context1, addNodeOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cluster_AddNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddNode'
type Cluster_AddNode_Call struct {
	*mock.Call
}

// AddNode is a helper method to define mock.On call
//   - context1 context.Context
//   - addNodeOptions *types.AddNodeOptions
func (_e *Cluster_Expecter) AddNode(context1 any, addNodeOptions any) *Cluster_AddNode_Call {
	return &Cluster_AddNode_Call{Call: _e.mock.On("AddNode", context1, addNodeOptions)}
}

func (_c *Cluster_AddNode_Call) Run(run func(context1 context.Context, addNodeOptions *types.AddNodeOptions)) *Cluster_AddNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.AddNodeOptions
		if args[1] != nil {
			arg1 = args[1].(*types.AddNodeOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cluster_AddNode_Call) Return(node *types.Node, err error) *Cluster_AddNode_Call {
	_c.Call.Return(node, err)
	return _c
}

func (_c *Cluster_AddNode_Call) RunAndReturn(run func(context1 context.Context, addNodeOptions *types.AddNodeOptions) (*types.Node, error)) *Cluster_AddNode_Call {
	_c.Call.Return(run)
	return _c
}

// AddPod provides a mock function for the type Cluster
func (_mock *Cluster) AddPod(ctx context.Context, podname string, desc string) (*types.Pod, error) {
	ret := _mock.Called(ctx, podname, desc)

	if len(ret) == 0 {
		panic("no return value specified for AddPod")
	}

	var r0 *types.Pod
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*types.Pod, error)); ok {
		return returnFunc(ctx, podname, desc)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *types.Pod); ok {
		r0 = returnFunc(ctx, podname, desc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Pod)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, podname, desc)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cluster_AddPod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPod'
type Cluster_AddPod_Call struct {
	*mock.Call
}

// AddPod is a helper method to define mock.On call
//   - ctx context.Context
//   - podname string
//   - desc string
func (_e *Cluster_Expecter) AddPod(ctx any, podname any, desc any) *Cluster_AddPod_Call {
	return &Cluster_AddPod_Call{Call: _e.mock.On("AddPod", ctx, podname, desc)}
}

func (_c *Cluster_AddPod_Call) Run(run func(ctx context.Context, podname string, desc string)) *Cluster_AddPod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Cluster_AddPod_Call) Return(pod *types.Pod, err error) *Cluster_AddPod_Call {
	_c.Call.Return(pod, err)
	return _c
}

func (_c *Cluster_AddPod_Call) RunAndReturn(run func(ctx context.Context, podname string, desc string) (*types.Pod, error)) *Cluster_AddPod_Call {
	_c.Call.Return(run)
	return _c
}

// BuildImage provides a mock function for the type Cluster
func (_mock *Cluster) BuildImage(ctx context.Context, opts *types.BuildOptions) (chan *types.BuildImageMessage, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for BuildImage")
	}

	var r0 chan *types.BuildImageMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.BuildOptions) (chan *types.BuildImageMessage, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.BuildOptions) chan *types.BuildImageMessage); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan *types.BuildImageMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types.BuildOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cluster_BuildImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildImage'
type Cluster_BuildImage_Call struct {
	*mock.Call
}

// BuildImage is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *types.BuildOptions
func (_e *Cluster_Expecter) BuildImage(ctx any, opts any) *Cluster_BuildImage_Call {
	return &Cluster_BuildImage_Call{Call: _e.mock.On("BuildImage", ctx, opts)}
}

func (_c *Cluster_BuildImage_Call) Run(run func(ctx context.Context, opts *types.BuildOptions)) *Cluster_BuildImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.BuildOptions
		if args[1] != nil {
			arg1 = args[1].(*types.BuildOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cluster_BuildImage_Call) Return(buildImageMessageCh chan *types.BuildImageMessage, err error) *Cluster_BuildImage_Call {
	_c.Call.Return(buildImageMessageCh, err)
	return _c
}

func (_c *Cluster_BuildImage_Call) RunAndReturn(run func(ctx context.Context, opts *types.BuildOptions) (chan *types.BuildImageMessage, error)) *Cluster_BuildImage_Call {
	_c.Call.Return(run)
	return _c
}

// CacheImage provides a mock function for the type Cluster
func (_mock *Cluster) CacheImage(ctx context.Context, opts *types.ImageOptions) (chan *types.CacheImageMessage, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for CacheImage")
	}

	var r0 chan *types.CacheImageMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.ImageOptions) (chan *types.CacheImageMessage, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.ImageOptions) chan *types.CacheImageMessage); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan *types.CacheImageMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types.ImageOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cluster_CacheImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CacheImage'
type Cluster_CacheImage_Call struct {
	*mock.Call
}

// CacheImage is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *types.ImageOptions
func (_e *Cluster_Expecter) CacheImage(ctx any, opts any) *Cluster_CacheImage_Call {
	return &Cluster_CacheImage_Call{Call: _e.mock.On("CacheImage", ctx, opts)}
}

func (_c *Cluster_CacheImage_Call) Run(run func(ctx context.Context, opts *types.ImageOptions)) *Cluster_CacheImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.ImageOptions
		if args[1] != nil {
			arg1 = args[1].(*types.ImageOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cluster_CacheImage_Call) Return(cacheImageMessageCh chan *types.CacheImageMessage, err error) *Cluster_CacheImage_Call {
	_c.Call.Return(cacheImageMessageCh, err)
	return _c
}

func (_c *Cluster_CacheImage_Call) RunAndReturn(run func(ctx context.Context, opts *types.ImageOptions) (chan *types.CacheImageMessage, error)) *Cluster_CacheImage_Call {
	_c.Call.Return(run)
	return _c
}

// CalculateCapacity provides a mock function for the type Cluster
func (_mock *Cluster) CalculateCapacity(context1 context.Context, deployOptions *types.DeployOptions) (*types.CapacityMessage, error) {
	ret := _mock.Called(context1, deployOptions)

	if len(ret) == 0 {
		panic("no return value specified for CalculateCapacity")
	}

	var r0 *types.CapacityMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.DeployOptions) (*types.CapacityMessage, error)); ok {
		return returnFunc(context1, deployOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.DeployOptions) *types.CapacityMessage); ok {
		r0 = returnFunc(context1, deployOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.CapacityMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types.DeployOptions) error); ok {
		r1 = returnFunc(context1, deployOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cluster_CalculateCapacity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CalculateCapacity'
type Cluster_CalculateCapacity_Call struct {
	*mock.Call
}

// CalculateCapacity is a helper method to define mock.On call
//   - context1 context.Context
//   - deployOptions *types.DeployOptions
func (_e *Cluster_Expecter) CalculateCapacity(context1 any, deployOptions any) *Cluster_CalculateCapacity_Call {
	return &Cluster_CalculateCapacity_Call{Call: _e.mock.On("CalculateCapacity", context1, deployOptions)}
}

func (_c *Cluster_CalculateCapacity_Call) Run(run func(context1 context.Context, deployOptions *types.DeployOptions)) *Cluster_CalculateCapacity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.DeployOptions
		if args[1] != nil {
			arg1 = args[1].(*types.DeployOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cluster_CalculateCapacity_Call) Return(capacityMessage *types.CapacityMessage, err error) *Cluster_CalculateCapacity_Call {
	_c.Call.Return(capacityMessage, err)
	return _c
}

func (_c *Cluster_CalculateCapacity_Call) RunAndReturn(run func(context1 context.Context, deployOptions *types.DeployOptions) (*types.CapacityMessage, error)) *Cluster_CalculateCapacity_Call {
	_c.Call.Return(run)
	return _c
}

// ConnectNetwork provides a mock function for the type Cluster
func (_mock *Cluster) ConnectNetwork(ctx context.Context, network string, target string, ipv4 string, ipv6 string) ([]string, error) {
	ret := _mock.Called(ctx, network, target, ipv4, ipv6)

	if len(ret) == 0 {
		panic("no return value specified for ConnectNetwork")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) ([]string, error)); ok {
		return returnFunc(ctx, network, target, ipv4, ipv6)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) []string); ok {
		r0 = returnFunc(ctx, network, target, ipv4, ipv6)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, network, target, ipv4, ipv6)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cluster_ConnectNetwork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConnectNetwork'
type Cluster_ConnectNetwork_Call struct {
	*mock.Call
}

// ConnectNetwork is a helper method to define mock.On call
//   - ctx context.Context
//   - network string
//   - target string
//   - ipv4 string
//   - ipv6 string
func (_e *Cluster_Expecter) ConnectNetwork(ctx any, network any, target any, ipv4 any, ipv6 any) *Cluster_ConnectNetwork_Call {
	return &Cluster_ConnectNetwork_Call{Call: _e.mock.On("ConnectNetwork", ctx, network, target, ipv4, ipv6)}
}

func (_c *Cluster_ConnectNetwork_Call) Run(run func(ctx context.Context, network string, target string, ipv4 string, ipv6 string)) *Cluster_ConnectNetwork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *Cluster_ConnectNetwork_Call) Return(strings []string, err error) *Cluster_ConnectNetwork_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *Cluster_ConnectNetwork_Call) RunAndReturn(run func(ctx context.Context, network string, target string, ipv4 string, ipv6 string) ([]string, error)) *Cluster_ConnectNetwork_Call {
	_c.Call.Return(run)
	return _c
}

// ControlWorkload provides a mock function for the type Cluster
func (_mock *Cluster) ControlWorkload(ctx context.Context, IDs []string, t string, force bool) (chan *types.ControlWorkloadMessage, error) {
	ret := _mock.Called(ctx, IDs, t, force)

	if len(ret) == 0 {
		panic("no return value specified for ControlWorkload")
	}

	var r0 chan *types.ControlWorkloadMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, string, bool) (chan *types.ControlWorkloadMessage, error)); ok {
		return returnFunc(ctx, IDs, t, force)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, string, bool) chan *types.ControlWorkloadMessage); ok {
		r0 = returnFunc(ctx, IDs, t, force)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan *types.ControlWorkloadMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, string, bool) error); ok {
		r1 = returnFunc(ctx, IDs, t, force)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cluster_ControlWorkload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ControlWorkload'
type Cluster_ControlWorkload_Call struct {
	*mock.Call
}

// ControlWorkload is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []string
//   - t string
//   - force bool
func (_e *Cluster_Expecter) ControlWorkload(ctx any, IDs any, t any, force any) *Cluster_ControlWorkload_Call {
	return &Cluster_ControlWorkload_Call{Call: _e.mock.On("ControlWorkload", ctx, IDs, t, force)}
}

func (_c *Cluster_ControlWorkload_Call) Run(run func(ctx context.Context, IDs []string, t string, force bool)) *Cluster_ControlWorkload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Cluster_ControlWorkload_Call) Return(controlWorkloadMessageCh chan *types.ControlWorkloadMessage, err error) *Cluster_ControlWorkload_Call {
	_c.Call.Return(controlWorkloadMessageCh, err)
	return _c
}

func (_c *Cluster_ControlWorkload_Call) RunAndReturn(run func(ctx context.Context, IDs []string, t string, force bool) (chan *types.ControlWorkloadMessage, error)) *Cluster_ControlWorkload_Call {
	_c.Call.Return(run)
	return _c
}

// Copy provides a mock function for the type Cluster
func (_mock *Cluster) Copy(ctx context.Context, opts *types.CopyOptions) (chan *types.CopyMessage, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Copy")
	}

	var r0 chan *types.CopyMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.CopyOptions) (chan *types.CopyMessage, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.CopyOptions) chan *types.CopyMessage); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan *types.CopyMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types.CopyOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cluster_Copy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Copy'
type Cluster_Copy_Call struct {
	*mock.Call
}

// Copy is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *types.CopyOptions
func (_e *Cluster_Expecter) Copy(ctx any, opts any) *Cluster_Copy_Call {
	return &Cluster_Copy_Call{Call: _e.mock.On("Copy", ctx, opts)}
}

func (_c *Cluster_Copy_Call) Run(run func(ctx context.Context, opts *types.CopyOptions)) *Cluster_Copy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.CopyOptions
		if args[1] != nil {
			arg1 = args[1].(*types.CopyOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cluster_Copy_Call) Return(copyMessageCh chan *types.CopyMessage, err error) *Cluster_Copy_Call {
	_c.Call.Return(copyMessageCh, err)
	return _c
}

func (_c *Cluster_Copy_Call) RunAndReturn(run func(ctx context.Context, opts *types.CopyOptions) (chan *types.CopyMessage, error)) *Cluster_Copy_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWorkload provides a mock function for the type Cluster
func (_mock *Cluster) CreateWorkload(ctx context.Context, opts *types.DeployOptions) (chan *types.CreateWorkloadMessage, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for CreateWorkload")
	}

	var r0 chan *types.CreateWorkloadMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.DeployOptions) (chan *types.CreateWorkloadMessage, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.DeployOptions) chan *types.CreateWorkloadMessage); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan *types.CreateWorkloadMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types.DeployOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cluster_CreateWorkload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWorkload'
type Cluster_CreateWorkload_Call struct {
	*mock.Call
}

// CreateWorkload is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *types.DeployOptions
func (_e *Cluster_Expecter) CreateWorkload(ctx any, opts any) *Cluster_CreateWorkload_Call {
	return &Cluster_CreateWorkload_Call{Call: _e.mock.On("CreateWorkload", ctx, opts)}
}

func (_c *Cluster_CreateWorkload_Call) Run(run func(ctx context.Context, opts *types.DeployOptions)) *Cluster_CreateWorkload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.DeployOptions
		if args[1] != nil {
			arg1 = args[1].(*types.DeployOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cluster_CreateWorkload_Call) Return(createWorkloadMessageCh chan *types.CreateWorkloadMessage, err error) *Cluster_CreateWorkload_Call {
	_c.Call.Return(createWorkloadMessageCh, err)
	return _c
}

func (_c *Cluster_CreateWorkload_Call) RunAndReturn(run func(ctx context.Context, opts *types.DeployOptions) (chan *types.CreateWorkloadMessage, error)) *Cluster_CreateWorkload_Call {
	_c.Call.Return(run)
	return _c
}

// DisconnectNetwork provides a mock function for the type Cluster
func (_mock *Cluster) DisconnectNetwork(ctx context.Context, network string, target string, force bool) error {
	ret := _mock.Called(ctx, network, target, force)

	if len(ret) == 0 {
		panic("no return value specified for DisconnectNetwork")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, bool) error); ok {
		r0 = returnFunc(ctx, network, target, force)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Cluster_DisconnectNetwork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisconnectNetwork'
type Cluster_DisconnectNetwork_Call struct {
	*mock.Call
}

// DisconnectNetwork is a helper method to define mock.On call
//   - ctx context.Context
//   - network string
//   - target string
//   - force bool
func (_e *Cluster_Expecter) DisconnectNetwork(ctx any, network any, target any, force any) *Cluster_DisconnectNetwork_Call {
	return &Cluster_DisconnectNetwork_Call{Call: _e.mock.On("DisconnectNetwork", ctx, network, target, force)}
}

func (_c *Cluster_DisconnectNetwork_Call) Run(run func(ctx context.Context, network string, target string, force bool)) *Cluster_DisconnectNetwork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Cluster_DisconnectNetwork_Call) Return(err error) *Cluster_DisconnectNetwork_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Cluster_DisconnectNetwork_Call) RunAndReturn(run func(ctx context.Context, network string, target string, force bool) error) *Cluster_DisconnectNetwork_Call {
	_c.Call.Return(run)
	return _c
}

// DissociateWorkload provides a mock function for the type Cluster
func (_mock *Cluster) DissociateWorkload(ctx context.Context, IDs []string) (chan *types.DissociateWorkloadMessage, error) {
	ret := _mock.Called(ctx, IDs)

	if len(ret) == 0 {
		panic("no return value specified for DissociateWorkload")
	}

	var r0 chan *types.DissociateWorkloadMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) (chan *types.DissociateWorkloadMessage, error)); ok {
		return returnFunc(ctx, IDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) chan *types.DissociateWorkloadMessage); ok {
		r0 = returnFunc(ctx, IDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan *types.DissociateWorkloadMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, IDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cluster_DissociateWorkload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DissociateWorkload'
type Cluster_DissociateWorkload_Call struct {
	*mock.Call
}

// DissociateWorkload is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []string
func (_e *Cluster_Expecter) DissociateWorkload(ctx any, IDs any) *Cluster_DissociateWorkload_Call {
	return &Cluster_DissociateWorkload_Call{Call: _e.mock.On("DissociateWorkload", ctx, IDs)}
}

func (_c *Cluster_DissociateWorkload_Call) Run(run func(ctx context.Context, IDs []string)) *Cluster_DissociateWorkload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cluster_DissociateWorkload_Call) Return(dissociateWorkloadMessageCh chan *types.DissociateWorkloadMessage, err error) *Cluster_DissociateWorkload_Call {
	_c.Call.Return(dissociateWorkloadMessageCh, err)
	return _c
}

func (_c *Cluster_DissociateWorkload_Call) RunAndReturn(run func(ctx context.Context, IDs []string) (chan *types.DissociateWorkloadMessage, error)) *Cluster_DissociateWorkload_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteWorkload provides a mock function for the type Cluster
func (_mock *Cluster) ExecuteWorkload(ctx context.Context, opts *types.ExecuteWorkloadOptions, inCh <-chan []byte) chan *types.AttachWorkloadMessage {
	ret := _mock.Called(ctx, opts, inCh)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteWorkload")
	}

	var r0 chan *types.AttachWorkloadMessage
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.ExecuteWorkloadOptions, <-chan []byte) chan *types.AttachWorkloadMessage); ok {
		r0 = returnFunc(ctx, opts, inCh)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan *types.AttachWorkloadMessage)
		}
	}
	return r0
}

// Cluster_ExecuteWorkload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteWorkload'
type Cluster_ExecuteWorkload_Call struct {
	*mock.Call
}

// ExecuteWorkload is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *types.ExecuteWorkloadOptions
//   - inCh <-chan []byte
func (_e *Cluster_Expecter) ExecuteWorkload(ctx any, opts any, inCh any) *Cluster_ExecuteWorkload_Call {
	return &Cluster_ExecuteWorkload_Call{Call: _e.mock.On("ExecuteWorkload", ctx, opts, inCh)}
}

func (_c *Cluster_ExecuteWorkload_Call) Run(run func(ctx context.Context, opts *types.ExecuteWorkloadOptions, inCh <-chan []byte)) *Cluster_ExecuteWorkload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.ExecuteWorkloadOptions
		if args[1] != nil {
			arg1 = args[1].(*types.ExecuteWorkloadOptions)
		}
		var arg2 <-chan []byte
		if args[2] != nil {
			arg2 = args[2].(<-chan []byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Cluster_ExecuteWorkload_Call) Return(attachWorkloadMessageCh chan *types.AttachWorkloadMessage) *Cluster_ExecuteWorkload_Call {
	_c.Call.Return(attachWorkloadMessageCh)
	return _c
}

func (_c *Cluster_ExecuteWorkload_Call) RunAndReturn(run func(ctx context.Context, opts *types.ExecuteWorkloadOptions, inCh <-chan []byte) chan *types.AttachWorkloadMessage) *Cluster_ExecuteWorkload_Call {
	_c.Call.Return(run)
	return _c
}

// Finalizer provides a mock function for the type Cluster
func (_mock *Cluster) Finalizer() {
	_mock.Called()
	return
}

// Cluster_Finalizer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Finalizer'
type Cluster_Finalizer_Call struct {
	*mock.Call
}

// Finalizer is a helper method to define mock.On call
func (_e *Cluster_Expecter) Finalizer() *Cluster_Finalizer_Call {
	return &Cluster_Finalizer_Call{Call: _e.mock.On("Finalizer")}
}

func (_c *Cluster_Finalizer_Call) Run(run func()) *Cluster_Finalizer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Cluster_Finalizer_Call) Return() *Cluster_Finalizer_Call {
	_c.Call.Return()
	return _c
}

func (_c *Cluster_Finalizer_Call) RunAndReturn(run func()) *Cluster_Finalizer_Call {
	_c.Run(run)
	return _c
}

// GetIdentifier provides a mock function for the type Cluster
func (_mock *Cluster) GetIdentifier() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetIdentifier")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Cluster_GetIdentifier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIdentifier'
type Cluster_GetIdentifier_Call struct {
	*mock.Call
}

// GetIdentifier is a helper method to define mock.On call
func (_e *Cluster_Expecter) GetIdentifier() *Cluster_GetIdentifier_Call {
	return &Cluster_GetIdentifier_Call{Call: _e.mock.On("GetIdentifier")}
}

func (_c *Cluster_GetIdentifier_Call) Run(run func()) *Cluster_GetIdentifier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Cluster_GetIdentifier_Call) Return(s string) *Cluster_GetIdentifier_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Cluster_GetIdentifier_Call) RunAndReturn(run func() string) *Cluster_GetIdentifier_Call {
	_c.Call.Return(run)
	return _c
}

// GetNode provides a mock function for the type Cluster
func (_mock *Cluster) GetNode(ctx context.Context, nodename string) (*types.Node, error) {
	ret := _mock.Called(ctx, nodename)

	if len(ret) == 0 {
		panic("no return value specified for GetNode")
	}

	var r0 *types.Node
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*types.Node, error)); ok {
		return returnFunc(ctx, nodename)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *types.Node); ok {
		r0 = returnFunc(ctx, nodename)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Node)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, nodename)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cluster_GetNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNode'
type Cluster_GetNode_Call struct {
	*mock.Call
}

// GetNode is a helper method to define mock.On call
//   - ctx context.Context
//   - nodename string
func (_e *Cluster_Expecter) GetNode(ctx any, nodename any) *Cluster_GetNode_Call {
	return &Cluster_GetNode_Call{Call: _e.mock.On("GetNode", ctx, nodename)}
}

func (_c *Cluster_GetNode_Call) Run(run func(ctx context.Context, nodename string)) *Cluster_GetNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cluster_GetNode_Call) Return(node *types.Node, err error) *Cluster_GetNode_Call {
	_c.Call.Return(node, err)
	return _c
}

func (_c *Cluster_GetNode_Call) RunAndReturn(run func(ctx context.Context, nodename string) (*types.Node, error)) *Cluster_GetNode_Call {
	_c.Call.Return(run)
	return _c
}

// GetNodeEngineInfo provides a mock function for the type Cluster
func (_mock *Cluster) GetNodeEngineInfo(ctx context.Context, nodename string) (*types0.Info, error) {
	ret := _mock.Called(ctx, nodename)

	if len(ret) == 0 {
		panic("no return value specified for GetNodeEngineInfo")
	}

	var r0 *types0.Info
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*types0.Info, error)); ok {
		return returnFunc(ctx, nodename)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *types0.Info); ok {
		r0 = returnFunc(ctx, nodename)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types0.Info)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, nodename)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cluster_GetNodeEngineInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNodeEngineInfo'
type Cluster_GetNodeEngineInfo_Call struct {
	*mock.Call
}

// GetNodeEngineInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - nodename string
func (_e *Cluster_Expecter) GetNodeEngineInfo(ctx any, nodename any) *Cluster_GetNodeEngineInfo_Call {
	return &Cluster_GetNodeEngineInfo_Call{Call: _e.mock.On("GetNodeEngineInfo", ctx, nodename)}
}

func (_c *Cluster_GetNodeEngineInfo_Call) Run(run func(ctx context.Context, nodename string)) *Cluster_GetNodeEngineInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cluster_GetNodeEngineInfo_Call) Return(info *types0.Info, err error) *Cluster_GetNodeEngineInfo_Call {
	_c.Call.Return(info, err)
	return _c
}

func (_c *Cluster_GetNodeEngineInfo_Call) RunAndReturn(run func(ctx context.Context, nodename string) (*types0.Info, error)) *Cluster_GetNodeEngineInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetNodeStatus provides a mock function for the type Cluster
func (_mock *Cluster) GetNodeStatus(ctx context.Context, nodename string) (*types.NodeStatus, error) {
	ret := _mock.Called(ctx, nodename)

	if len(ret) == 0 {
		panic("no return value specified for GetNodeStatus")
	}

	var r0 *types.NodeStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*types.NodeStatus, error)); ok {
		return returnFunc(ctx, nodename)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *types.NodeStatus); ok {
		r0 = returnFunc(ctx, nodename)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.NodeStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, nodename)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cluster_GetNodeStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNodeStatus'
type Cluster_GetNodeStatus_Call struct {
	*mock.Call
}

// GetNodeStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - nodename string
func (_e *Cluster_Expecter) GetNodeStatus(ctx any, nodename any) *Cluster_GetNodeStatus_Call {
	return &Cluster_GetNodeStatus_Call{Call: _e.mock.On("GetNodeStatus", ctx, nodename)}
}

func (_c *Cluster_GetNodeStatus_Call) Run(run func(ctx context.Context, nodename string)) *Cluster_GetNodeStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cluster_GetNodeStatus_Call) Return(nodeStatus *types.NodeStatus, err error) *Cluster_GetNodeStatus_Call {
	_c.Call.Return(nodeStatus, err)
	return _c
}

func (_c *Cluster_GetNodeStatus_Call) RunAndReturn(run func(ctx context.Context, nodename string) (*types.NodeStatus, error)) *Cluster_GetNodeStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetPod provides a mock function for the type Cluster
func (_mock *Cluster) GetPod(ctx context.Context, podname string) (*types.Pod, error) {
	ret := _mock.Called(ctx, podname)

	if len(ret) == 0 {
		panic("no return value specified for GetPod")
	}

	var r0 *types.Pod
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*types.Pod, error)); ok {
		return returnFunc(ctx, podname)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *types.Pod); ok {
		r0 = returnFunc(ctx, podname)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Pod)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, podname)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cluster_GetPod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPod'
type Cluster_GetPod_Call struct {
	*mock.Call
}

// GetPod is a helper method to define mock.On call
//   - ctx context.Context
//   - podname string
func (_e *Cluster_Expecter) GetPod(ctx any, podname any) *Cluster_GetPod_Call {
	return &Cluster_GetPod_Call{Call: _e.mock.On("GetPod", ctx, podname)}
}

func (_c *Cluster_GetPod_Call) Run(run func(ctx context.Context, podname string)) *Cluster_GetPod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cluster_GetPod_Call) Return(pod *types.Pod, err error) *Cluster_GetPod_Call {
	_c.Call.Return(pod, err)
	return _c
}

func (_c *Cluster_GetPod_Call) RunAndReturn(run func(ctx context.Context, podname string) (*types.Pod, error)) *Cluster_GetPod_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkload provides a mock function for the type Cluster
func (_mock *Cluster) GetWorkload(ctx context.Context, id string) (*types.Workload, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkload")
	}

	var r0 *types.Workload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*types.Workload, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *types.Workload); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Workload)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cluster_GetWorkload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkload'
type Cluster_GetWorkload_Call struct {
	*mock.Call
}

// GetWorkload is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Cluster_Expecter) GetWorkload(ctx any, id any) *Cluster_GetWorkload_Call {
	return &Cluster_GetWorkload_Call{Call: _e.mock.On("GetWorkload", ctx, id)}
}

func (_c *Cluster_GetWorkload_Call) Run(run func(ctx context.Context, id string)) *Cluster_GetWorkload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cluster_GetWorkload_Call) Return(workload *types.Workload, err error) *Cluster_GetWorkload_Call {
	_c.Call.Return(workload, err)
	return _c
}

func (_c *Cluster_GetWorkload_Call) RunAndReturn(run func(ctx context.Context, id string) (*types.Workload, error)) *Cluster_GetWorkload_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkloads provides a mock function for the type Cluster
func (_mock *Cluster) GetWorkloads(ctx context.Context, IDs []string) ([]*types.Workload, error) {
	ret := _mock.Called(ctx, IDs)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkloads")
	}

	var r0 []*types.Workload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]*types.Workload, error)); ok {
		return returnFunc(ctx, IDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []*types.Workload); ok {
		r0 = returnFunc(ctx, IDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.Workload)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, IDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cluster_GetWorkloads_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkloads'
type Cluster_GetWorkloads_Call struct {
	*mock.Call
}

// GetWorkloads is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []string
func (_e *Cluster_Expecter) GetWorkloads(ctx any, IDs any) *Cluster_GetWorkloads_Call {
	return &Cluster_GetWorkloads_Call{Call: _e.mock.On("GetWorkloads", ctx, IDs)}
}

func (_c *Cluster_GetWorkloads_Call) Run(run func(ctx context.Context, IDs []string)) *Cluster_GetWorkloads_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cluster_GetWorkloads_Call) Return(workloads []*types.Workload, err error) *Cluster_GetWorkloads_Call {
	_c.Call.Return(workloads, err)
	return _c
}

func (_c *Cluster_GetWorkloads_Call) RunAndReturn(run func(ctx context.Context, IDs []string) ([]*types.Workload, error)) *Cluster_GetWorkloads_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkloadsStatus provides a mock function for the type Cluster
func (_mock *Cluster) GetWorkloadsStatus(ctx context.Context, IDs []string) ([]*types.StatusMeta, error) {
	ret := _mock.Called(ctx, IDs)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkloadsStatus")
	}

	var r0 []*types.StatusMeta
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]*types.StatusMeta, error)); ok {
		return returnFunc(ctx, IDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []*types.StatusMeta); ok {
		r0 = returnFunc(ctx, IDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.StatusMeta)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, IDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cluster_GetWorkloadsStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkloadsStatus'
type Cluster_GetWorkloadsStatus_Call struct {
	*mock.Call
}

// GetWorkloadsStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []string
func (_e *Cluster_Expecter) GetWorkloadsStatus(ctx any, IDs any) *Cluster_GetWorkloadsStatus_Call {
	return &Cluster_GetWorkloadsStatus_Call{Call: _e.mock.On("GetWorkloadsStatus", ctx, IDs)}
}

func (_c *Cluster_GetWorkloadsStatus_Call) Run(run func(ctx context.Context, IDs []string)) *Cluster_GetWorkloadsStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cluster_GetWorkloadsStatus_Call) Return(statusMetas []*types.StatusMeta, err error) *Cluster_GetWorkloadsStatus_Call {
	_c.Call.Return(statusMetas, err)
	return _c
}

func (_c *Cluster_GetWorkloadsStatus_Call) RunAndReturn(run func(ctx context.Context, IDs []string) ([]*types.StatusMeta, error)) *Cluster_GetWorkloadsStatus_Call {
	_c.Call.Return(run)
	return _c
}

// ListImage provides a mock function for the type Cluster
func (_mock *Cluster) ListImage(ctx context.Context, opts *types.ImageOptions) (chan *types.ListImageMessage, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListImage")
	}

	var r0 chan *types.ListImageMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.ImageOptions) (chan *types.ListImageMessage, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.ImageOptions) chan *types.ListImageMessage); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan *types.ListImageMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types.ImageOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cluster_ListImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListImage'
type Cluster_ListImage_Call struct {
	*mock.Call
}

// ListImage is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *types.ImageOptions
func (_e *Cluster_Expecter) ListImage(ctx any, opts any) *Cluster_ListImage_Call {
	return &Cluster_ListImage_Call{Call: _e.mock.On("ListImage", ctx, opts)}
}

func (_c *Cluster_ListImage_Call) Run(run func(ctx context.Context, opts *types.ImageOptions)) *Cluster_ListImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.ImageOptions
		if args[1] != nil {
			arg1 = args[1].(*types.ImageOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cluster_ListImage_Call) Return(listImageMessageCh chan *types.ListImageMessage, err error) *Cluster_ListImage_Call {
	_c.Call.Return(listImageMessageCh, err)
	return _c
}

func (_c *Cluster_ListImage_Call) RunAndReturn(run func(ctx context.Context, opts *types.ImageOptions) (chan *types.ListImageMessage, error)) *Cluster_ListImage_Call {
	_c.Call.Return(run)
	return _c
}

// ListNetworks provides a mock function for the type Cluster
func (_mock *Cluster) ListNetworks(ctx context.Context, podname string, driver string) ([]*types0.Network, error) {
	ret := _mock.Called(ctx, podname, driver)

	if len(ret) == 0 {
		panic("no return value specified for ListNetworks")
	}

	var r0 []*types0.Network
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]*types0.Network, error)); ok {
		return returnFunc(ctx, podname, driver)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []*types0.Network); ok {
		r0 = returnFunc(ctx, podname, driver)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types0.Network)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, podname, driver)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cluster_ListNetworks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNetworks'
type Cluster_ListNetworks_Call struct {
	*mock.Call
}

// ListNetworks is a helper method to define mock.On call
//   - ctx context.Context
//   - podname string
//   - driver string
func (_e *Cluster_Expecter) ListNetworks(ctx any, podname any, driver any) *Cluster_ListNetworks_Call {
	return &Cluster_ListNetworks_Call{Call: _e.mock.On("ListNetworks", ctx, podname, driver)}
}

func (_c *Cluster_ListNetworks_Call) Run(run func(ctx context.Context, podname string, driver string)) *Cluster_ListNetworks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Cluster_ListNetworks_Call) Return(networks []*types0.Network, err error) *Cluster_ListNetworks_Call {
	_c.Call.Return(networks, err)
	return _c
}

func (_c *Cluster_ListNetworks_Call) RunAndReturn(run func(ctx context.Context, podname string, driver string) ([]*types0.Network, error)) *Cluster_ListNetworks_Call {
	_c.Call.Return(run)
	return _c
}

// ListNodeWorkloads provides a mock function for the type Cluster
func (_mock *Cluster) ListNodeWorkloads(ctx context.Context, nodename string, labels map[string]string) ([]*types.Workload, error) {
	ret := _mock.Called(ctx, nodename, labels)

	if len(ret) == 0 {
		panic("no return value specified for ListNodeWorkloads")
	}

	var r0 []*types.Workload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]string) ([]*types.Workload, error)); ok {
		return returnFunc(ctx, nodename, labels)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]string) []*types.Workload); ok {
		r0 = returnFunc(ctx, nodename, labels)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.Workload)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, map[string]string) error); ok {
		r1 = returnFunc(ctx, nodename, labels)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cluster_ListNodeWorkloads_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNodeWorkloads'
type Cluster_ListNodeWorkloads_Call struct {
	*mock.Call
}

// ListNodeWorkloads is a helper method to define mock.On call
//   - ctx context.Context
//   - nodename string
//   - labels map[string]string
func (_e *Cluster_Expecter) ListNodeWorkloads(ctx any, nodename any, labels any) *Cluster_ListNodeWorkloads_Call {
	return &Cluster_ListNodeWorkloads_Call{Call: _e.mock.On("ListNodeWorkloads", ctx, nodename, labels)}
}

func (_c *Cluster_ListNodeWorkloads_Call) Run(run func(ctx context.Context, nodename string, labels map[string]string)) *Cluster_ListNodeWorkloads_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]string
		if args[2] != nil {
			arg2 = args[2].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Cluster_ListNodeWorkloads_Call) Return(workloads []*types.Workload, err error) *Cluster_ListNodeWorkloads_Call {
	_c.Call.Return(workloads, err)
	return _c
}

func (_c *Cluster_ListNodeWorkloads_Call) RunAndReturn(run func(ctx context.Context, nodename string, labels map[string]string) ([]*types.Workload, error)) *Cluster_ListNodeWorkloads_Call {
	_c.Call.Return(run)
	return _c
}

// ListPodNodes provides a mock function for the type Cluster
func (_mock *Cluster) ListPodNodes(context1 context.Context, listNodesOptions *types.ListNodesOptions) (<-chan *types.Node, error) {
	ret := _mock.Called(context1, listNodesOptions)

	if len(ret) == 0 {
		panic("no return value specified for ListPodNodes")
	}

	var r0 <-chan *types.Node
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.ListNodesOptions) (<-chan *types.Node, error)); ok {
		return returnFunc(context1, listNodesOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.ListNodesOptions) <-chan *types.Node); ok {
		r0 = returnFunc(context1, listNodesOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *types.Node)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types.ListNodesOptions) error); ok {
		r1 = returnFunc(context1, listNodesOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cluster_ListPodNodes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPodNodes'
type Cluster_ListPodNodes_Call struct {
	*mock.Call
}

// ListPodNodes is a helper method to define mock.On call
//   - context1 context.Context
//   - listNodesOptions *types.ListNodesOptions
func (_e *Cluster_Expecter) ListPodNodes(context1 any, listNodesOptions any) *Cluster_ListPodNodes_Call {
	return &Cluster_ListPodNodes_Call{Call: _e.mock.On("ListPodNodes", context1, listNodesOptions)}
}

func (_c *Cluster_ListPodNodes_Call) Run(run func(context1 context.Context, listNodesOptions *types.ListNodesOptions)) *Cluster_ListPodNodes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.ListNodesOptions
		if args[1] != nil {
			arg1 = args[1].(*types.ListNodesOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cluster_ListPodNodes_Call) Return(nodeCh <-chan *types.Node, err error) *Cluster_ListPodNodes_Call {
	_c.Call.Return(nodeCh, err)
	return _c
}

func (_c *Cluster_ListPodNodes_Call) RunAndReturn(run func(context1 context.Context, listNodesOptions *types.ListNodesOptions) (<-chan *types.Node, error)) *Cluster_ListPodNodes_Call {
	_c.Call.Return(run)
	return _c
}

// ListPods provides a mock function for the type Cluster
func (_mock *Cluster) ListPods(ctx context.Context) ([]*types.Pod, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPods")
	}

	var r0 []*types.Pod
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*types.Pod, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*types.Pod); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.Pod)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cluster_ListPods_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPods'
type Cluster_ListPods_Call struct {
	*mock.Call
}

// ListPods is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Cluster_Expecter) ListPods(ctx any) *Cluster_ListPods_Call {
	return &Cluster_ListPods_Call{Call: _e.mock.On("ListPods", ctx)}
}

func (_c *Cluster_ListPods_Call) Run(run func(ctx context.Context)) *Cluster_ListPods_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Cluster_ListPods_Call) Return(pods []*types.Pod, err error) *Cluster_ListPods_Call {
	_c.Call.Return(pods, err)
	return _c
}

func (_c *Cluster_ListPods_Call) RunAndReturn(run func(ctx context.Context) ([]*types.Pod, error)) *Cluster_ListPods_Call {
	_c.Call.Return(run)
	return _c
}

// ListWorkloads provides a mock function for the type Cluster
func (_mock *Cluster) ListWorkloads(ctx context.Context, opts *types.ListWorkloadsOptions) ([]*types.Workload, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListWorkloads")
	}

	var r0 []*types.Workload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.ListWorkloadsOptions) ([]*types.Workload, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.ListWorkloadsOptions) []*types.Workload); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.Workload)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types.ListWorkloadsOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cluster_ListWorkloads_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWorkloads'
type Cluster_ListWorkloads_Call struct {
	*mock.Call
}

// ListWorkloads is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *types.ListWorkloadsOptions
func (_e *Cluster_Expecter) ListWorkloads(ctx any, opts any) *Cluster_ListWorkloads_Call {
	return &Cluster_ListWorkloads_Call{Call: _e.mock.On("ListWorkloads", ctx, opts)}
}

func (_c *Cluster_ListWorkloads_Call) Run(run func(ctx context.Context, opts *types.ListWorkloadsOptions)) *Cluster_ListWorkloads_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.ListWorkloadsOptions
		if args[1] != nil {
			arg1 = args[1].(*types.ListWorkloadsOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cluster_ListWorkloads_Call) Return(workloads []*types.Workload, err error) *Cluster_ListWorkloads_Call {
	_c.Call.Return(workloads, err)
	return _c
}

func (_c *Cluster_ListWorkloads_Call) RunAndReturn(run func(ctx context.Context, opts *types.ListWorkloadsOptions) ([]*types.Workload, error)) *Cluster_ListWorkloads_Call {
	_c.Call.Return(run)
	return _c
}

// LogStream provides a mock function for the type Cluster
func (_mock *Cluster) LogStream(ctx context.Context, opts *types.LogStreamOptions) (chan *types.LogStreamMessage, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for LogStream")
	}

	var r0 chan *types.LogStreamMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.LogStreamOptions) (chan *types.LogStreamMessage, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.LogStreamOptions) chan *types.LogStreamMessage); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan *types.LogStreamMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types.LogStreamOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cluster_LogStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogStream'
type Cluster_LogStream_Call struct {
	*mock.Call
}

// LogStream is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *types.LogStreamOptions
func (_e *Cluster_Expecter) LogStream(ctx any, opts any) *Cluster_LogStream_Call {
	return &Cluster_LogStream_Call{Call: _e.mock.On("LogStream", ctx, opts)}
}

func (_c *Cluster_LogStream_Call) Run(run func(ctx context.Context, opts *types.LogStreamOptions)) *Cluster_LogStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.LogStreamOptions
		if args[1] != nil {
			arg1 = args[1].(*types.LogStreamOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cluster_LogStream_Call) Return(logStreamMessageCh chan *types.LogStreamMessage, err error) *Cluster_LogStream_Call {
	_c.Call.Return(logStreamMessageCh, err)
	return _c
}

func (_c *Cluster_LogStream_Call) RunAndReturn(run func(ctx context.Context, opts *types.LogStreamOptions) (chan *types.LogStreamMessage, error)) *Cluster_LogStream_Call {
	_c.Call.Return(run)
	return _c
}

// NodeResource provides a mock function for the type Cluster
func (_mock *Cluster) NodeResource(ctx context.Context, nodename string, fix bool) (*types.NodeResourceInfo, error) {
	ret := _mock.Called(ctx, nodename, fix)

	if len(ret) == 0 {
		panic("no return value specified for NodeResource")
	}

	var r0 *types.NodeResourceInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) (*types.NodeResourceInfo, error)); ok {
		return returnFunc(ctx, nodename, fix)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) *types.NodeResourceInfo); ok {
		r0 = returnFunc(ctx, nodename, fix)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.NodeResourceInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = returnFunc(ctx, nodename, fix)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cluster_NodeResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NodeResource'
type Cluster_NodeResource_Call struct {
	*mock.Call
}

// NodeResource is a helper method to define mock.On call
//   - ctx context.Context
//   - nodename string
//   - fix bool
func (_e *Cluster_Expecter) NodeResource(ctx any, nodename any, fix any) *Cluster_NodeResource_Call {
	return &Cluster_NodeResource_Call{Call: _e.mock.On("NodeResource", ctx, nodename, fix)}
}

func (_c *Cluster_NodeResource_Call) Run(run func(ctx context.Context, nodename string, fix bool)) *Cluster_NodeResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Cluster_NodeResource_Call) Return(nodeResourceInfo *types.NodeResourceInfo, err error) *Cluster_NodeResource_Call {
	_c.Call.Return(nodeResourceInfo, err)
	return _c
}

func (_c *Cluster_NodeResource_Call) RunAndReturn(run func(ctx context.Context, nodename string, fix bool) (*types.NodeResourceInfo, error)) *Cluster_NodeResource_Call {
	_c.Call.Return(run)
	return _c
}

// NodeStatusStream provides a mock function for the type Cluster
func (_mock *Cluster) NodeStatusStream(ctx context.Context) chan *types.NodeStatus {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for NodeStatusStream")
	}

	var r0 chan *types.NodeStatus
	if returnFunc, ok := ret.Get(0).(func(context.Context) chan *types.NodeStatus); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan *types.NodeStatus)
		}
	}
	return r0
}

// Cluster_NodeStatusStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NodeStatusStream'
type Cluster_NodeStatusStream_Call struct {
	*mock.Call
}

// NodeStatusStream is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Cluster_Expecter) NodeStatusStream(ctx any) *Cluster_NodeStatusStream_Call {
	return &Cluster_NodeStatusStream_Call{Call: _e.mock.On("NodeStatusStream", ctx)}
}

func (_c *Cluster_NodeStatusStream_Call) Run(run func(ctx context.Context)) *Cluster_NodeStatusStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Cluster_NodeStatusStream_Call) Return(nodeStatusCh chan *types.NodeStatus) *Cluster_NodeStatusStream_Call {
	_c.Call.Return(nodeStatusCh)
	return _c
}

func (_c *Cluster_NodeStatusStream_Call) RunAndReturn(run func(ctx context.Context) chan *types.NodeStatus) *Cluster_NodeStatusStream_Call {
	_c.Call.Return(run)
	return _c
}

// PodResource provides a mock function for the type Cluster
func (_mock *Cluster) PodResource(ctx context.Context, podname string) (chan *types.NodeResourceInfo, error) {
	ret := _mock.Called(ctx, podname)

	if len(ret) == 0 {
		panic("no return value specified for PodResource")
	}

	var r0 chan *types.NodeResourceInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (chan *types.NodeResourceInfo, error)); ok {
		return returnFunc(ctx, podname)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) chan *types.NodeResourceInfo); ok {
		r0 = returnFunc(ctx, podname)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan *types.NodeResourceInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, podname)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cluster_PodResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PodResource'
type Cluster_PodResource_Call struct {
	*mock.Call
}

// PodResource is a helper method to define mock.On call
//   - ctx context.Context
//   - podname string
func (_e *Cluster_Expecter) PodResource(ctx any, podname any) *Cluster_PodResource_Call {
	return &Cluster_PodResource_Call{Call: _e.mock.On("PodResource", ctx, podname)}
}

func (_c *Cluster_PodResource_Call) Run(run func(ctx context.Context, podname string)) *Cluster_PodResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cluster_PodResource_Call) Return(nodeResourceInfoCh chan *types.NodeResourceInfo, err error) *Cluster_PodResource_Call {
	_c.Call.Return(nodeResourceInfoCh, err)
	return _c
}

func (_c *Cluster_PodResource_Call) RunAndReturn(run func(ctx context.Context, podname string) (chan *types.NodeResourceInfo, error)) *Cluster_PodResource_Call {
	_c.Call.Return(run)
	return _c
}

// RawEngine provides a mock function for the type Cluster
func (_mock *Cluster) RawEngine(ctx context.Context, opts *types.RawEngineOptions) (*types.RawEngineMessage, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for RawEngine")
	}

	var r0 *types.RawEngineMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.RawEngineOptions) (*types.RawEngineMessage, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.RawEngineOptions) *types.RawEngineMessage); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.RawEngineMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types.RawEngineOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cluster_RawEngine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RawEngine'
type Cluster_RawEngine_Call struct {
	*mock.Call
}

// RawEngine is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *types.RawEngineOptions
func (_e *Cluster_Expecter) RawEngine(ctx any, opts any) *Cluster_RawEngine_Call {
	return &Cluster_RawEngine_Call{Call: _e.mock.On("RawEngine", ctx, opts)}
}

func (_c *Cluster_RawEngine_Call) Run(run func(ctx context.Context, opts *types.RawEngineOptions)) *Cluster_RawEngine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.RawEngineOptions
		if args[1] != nil {
			arg1 = args[1].(*types.RawEngineOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cluster_RawEngine_Call) Return(rawEngineMessage *types.RawEngineMessage, err error) *Cluster_RawEngine_Call {
	_c.Call.Return(rawEngineMessage, err)
	return _c
}

func (_c *Cluster_RawEngine_Call) RunAndReturn(run func(ctx context.Context, opts *types.RawEngineOptions) (*types.RawEngineMessage, error)) *Cluster_RawEngine_Call {
	_c.Call.Return(run)
	return _c
}

// ReallocResource provides a mock function for the type Cluster
func (_mock *Cluster) ReallocResource(ctx context.Context, opts *types.ReallocOptions) error {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for ReallocResource")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.ReallocOptions) error); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Cluster_ReallocResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReallocResource'
type Cluster_ReallocResource_Call struct {
	*mock.Call
}

// ReallocResource is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *types.ReallocOptions
func (_e *Cluster_Expecter) ReallocResource(ctx any, opts any) *Cluster_ReallocResource_Call {
	return &Cluster_ReallocResource_Call{Call: _e.mock.On("ReallocResource", ctx, opts)}
}

func (_c *Cluster_ReallocResource_Call) Run(run func(ctx context.Context, opts *types.ReallocOptions)) *Cluster_ReallocResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.ReallocOptions
		if args[1] != nil {
			arg1 = args[1].(*types.ReallocOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cluster_ReallocResource_Call) Return(err error) *Cluster_ReallocResource_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Cluster_ReallocResource_Call) RunAndReturn(run func(ctx context.Context, opts *types.ReallocOptions) error) *Cluster_ReallocResource_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveImage provides a mock function for the type Cluster
func (_mock *Cluster) RemoveImage(ctx context.Context, opts *types.ImageOptions) (chan *types.RemoveImageMessage, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for RemoveImage")
	}

	var r0 chan *types.RemoveImageMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.ImageOptions) (chan *types.RemoveImageMessage, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.ImageOptions) chan *types.RemoveImageMessage); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan *types.RemoveImageMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types.ImageOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cluster_RemoveImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveImage'
type Cluster_RemoveImage_Call struct {
	*mock.Call
}

// RemoveImage is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *types.ImageOptions
func (_e *Cluster_Expecter) RemoveImage(ctx any, opts any) *Cluster_RemoveImage_Call {
	return &Cluster_RemoveImage_Call{Call: _e.mock.On("RemoveImage", ctx, opts)}
}

func (_c *Cluster_RemoveImage_Call) Run(run func(ctx context.Context, opts *types.ImageOptions)) *Cluster_RemoveImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.ImageOptions
		if args[1] != nil {
			arg1 = args[1].(*types.ImageOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cluster_RemoveImage_Call) Return(removeImageMessageCh chan *types.RemoveImageMessage, err error) *Cluster_RemoveImage_Call {
	_c.Call.Return(removeImageMessageCh, err)
	return _c
}

func (_c *Cluster_RemoveImage_Call) RunAndReturn(run func(ctx context.Context, opts *types.ImageOptions) (chan *types.RemoveImageMessage, error)) *Cluster_RemoveImage_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveNode provides a mock function for the type Cluster
func (_mock *Cluster) RemoveNode(ctx context.Context, nodename string) error {
	ret := _mock.Called(ctx, nodename)

	if len(ret) == 0 {
		panic("no return value specified for RemoveNode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, nodename)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Cluster_RemoveNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveNode'
type Cluster_RemoveNode_Call struct {
	*mock.Call
}

// RemoveNode is a helper method to define mock.On call
//   - ctx context.Context
//   - nodename string
func (_e *Cluster_Expecter) RemoveNode(ctx any, nodename any) *Cluster_RemoveNode_Call {
	return &Cluster_RemoveNode_Call{Call: _e.mock.On("RemoveNode", ctx, nodename)}
}

func (_c *Cluster_RemoveNode_Call) Run(run func(ctx context.Context, nodename string)) *Cluster_RemoveNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cluster_RemoveNode_Call) Return(err error) *Cluster_RemoveNode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Cluster_RemoveNode_Call) RunAndReturn(run func(ctx context.Context, nodename string) error) *Cluster_RemoveNode_Call {
	_c.Call.Return(run)
	return _c
}

// RemovePod provides a mock function for the type Cluster
func (_mock *Cluster) RemovePod(ctx context.Context, podname string) error {
	ret := _mock.Called(ctx, podname)

	if len(ret) == 0 {
		panic("no return value specified for RemovePod")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, podname)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Cluster_RemovePod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemovePod'
type Cluster_RemovePod_Call struct {
	*mock.Call
}

// RemovePod is a helper method to define mock.On call
//   - ctx context.Context
//   - podname string
func (_e *Cluster_Expecter) RemovePod(ctx any, podname any) *Cluster_RemovePod_Call {
	return &Cluster_RemovePod_Call{Call: _e.mock.On("RemovePod", ctx, podname)}
}

func (_c *Cluster_RemovePod_Call) Run(run func(ctx context.Context, podname string)) *Cluster_RemovePod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cluster_RemovePod_Call) Return(err error) *Cluster_RemovePod_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Cluster_RemovePod_Call) RunAndReturn(run func(ctx context.Context, podname string) error) *Cluster_RemovePod_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveWorkload provides a mock function for the type Cluster
func (_mock *Cluster) RemoveWorkload(ctx context.Context, IDs []string, force bool) (chan *types.RemoveWorkloadMessage, error) {
	ret := _mock.Called(ctx, IDs, force)

	if len(ret) == 0 {
		panic("no return value specified for RemoveWorkload")
	}

	var r0 chan *types.RemoveWorkloadMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, bool) (chan *types.RemoveWorkloadMessage, error)); ok {
		return returnFunc(ctx, IDs, force)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, bool) chan *types.RemoveWorkloadMessage); ok {
		r0 = returnFunc(ctx, IDs, force)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan *types.RemoveWorkloadMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, bool) error); ok {
		r1 = returnFunc(ctx, IDs, force)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cluster_RemoveWorkload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveWorkload'
type Cluster_RemoveWorkload_Call struct {
	*mock.Call
}

// RemoveWorkload is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []string
//   - force bool
func (_e *Cluster_Expecter) RemoveWorkload(ctx any, IDs any, force any) *Cluster_RemoveWorkload_Call {
	return &Cluster_RemoveWorkload_Call{Call: _e.mock.On("RemoveWorkload", ctx, IDs, force)}
}

func (_c *Cluster_RemoveWorkload_Call) Run(run func(ctx context.Context, IDs []string, force bool)) *Cluster_RemoveWorkload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Cluster_RemoveWorkload_Call) Return(removeWorkloadMessageCh chan *types.RemoveWorkloadMessage, err error) *Cluster_RemoveWorkload_Call {
	_c.Call.Return(removeWorkloadMessageCh, err)
	return _c
}

func (_c *Cluster_RemoveWorkload_Call) RunAndReturn(run func(ctx context.Context, IDs []string, force bool) (chan *types.RemoveWorkloadMessage, error)) *Cluster_RemoveWorkload_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveWorkloadSync provides a mock function for the type Cluster
func (_mock *Cluster) RemoveWorkloadSync(ctx context.Context, IDs []string) error {
	ret := _mock.Called(ctx, IDs)

	if len(ret) == 0 {
		panic("no return value specified for RemoveWorkloadSync")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = returnFunc(ctx, IDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Cluster_RemoveWorkloadSync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveWorkloadSync'
type Cluster_RemoveWorkloadSync_Call struct {
	*mock.Call
}

// RemoveWorkloadSync is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []string
func (_e *Cluster_Expecter) RemoveWorkloadSync(ctx any, IDs any) *Cluster_RemoveWorkloadSync_Call {
	return &Cluster_RemoveWorkloadSync_Call{Call: _e.mock.On("RemoveWorkloadSync", ctx, IDs)}
}

func (_c *Cluster_RemoveWorkloadSync_Call) Run(run func(ctx context.Context, IDs []string)) *Cluster_RemoveWorkloadSync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cluster_RemoveWorkloadSync_Call) Return(err error) *Cluster_RemoveWorkloadSync_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Cluster_RemoveWorkloadSync_Call) RunAndReturn(run func(ctx context.Context, IDs []string) error) *Cluster_RemoveWorkloadSync_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceWorkload provides a mock function for the type Cluster
func (_mock *Cluster) ReplaceWorkload(ctx context.Context, opts *types.ReplaceOptions) (chan *types.ReplaceWorkloadMessage, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceWorkload")
	}

	var r0 chan *types.ReplaceWorkloadMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.ReplaceOptions) (chan *types.ReplaceWorkloadMessage, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.ReplaceOptions) chan *types.ReplaceWorkloadMessage); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan *types.ReplaceWorkloadMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types.ReplaceOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cluster_ReplaceWorkload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceWorkload'
type Cluster_ReplaceWorkload_Call struct {
	*mock.Call
}

// ReplaceWorkload is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *types.ReplaceOptions
func (_e *Cluster_Expecter) ReplaceWorkload(ctx any, opts any) *Cluster_ReplaceWorkload_Call {
	return &Cluster_ReplaceWorkload_Call{Call: _e.mock.On("ReplaceWorkload", ctx, opts)}
}

func (_c *Cluster_ReplaceWorkload_Call) Run(run func(ctx context.Context, opts *types.ReplaceOptions)) *Cluster_ReplaceWorkload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.ReplaceOptions
		if args[1] != nil {
			arg1 = args[1].(*types.ReplaceOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cluster_ReplaceWorkload_Call) Return(replaceWorkloadMessageCh chan *types.ReplaceWorkloadMessage, err error) *Cluster_ReplaceWorkload_Call {
	_c.Call.Return(replaceWorkloadMessageCh, err)
	return _c
}

func (_c *Cluster_ReplaceWorkload_Call) RunAndReturn(run func(ctx context.Context, opts *types.ReplaceOptions) (chan *types.ReplaceWorkloadMessage, error)) *Cluster_ReplaceWorkload_Call {
	_c.Call.Return(run)
	return _c
}

// RunAndWait provides a mock function for the type Cluster
func (_mock *Cluster) RunAndWait(ctx context.Context, opts *types.DeployOptions, inCh <-chan []byte) ([]string, <-chan *types.AttachWorkloadMessage, error) {
	ret := _mock.Called(ctx, opts, inCh)

	if len(ret) == 0 {
		panic("no return value specified for RunAndWait")
	}

	var r0 []string
	var r1 <-chan *types.AttachWorkloadMessage
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.DeployOptions, <-chan []byte) ([]string, <-chan *types.AttachWorkloadMessage, error)); ok {
		return returnFunc(ctx, opts, inCh)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.DeployOptions, <-chan []byte) []string); ok {
		r0 = returnFunc(ctx, opts, inCh)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types.DeployOptions, <-chan []byte) <-chan *types.AttachWorkloadMessage); ok {
		r1 = returnFunc(ctx, opts, inCh)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(<-chan *types.AttachWorkloadMessage)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *types.DeployOptions, <-chan []byte) error); ok {
		r2 = returnFunc(ctx, opts, inCh)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Cluster_RunAndWait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunAndWait'
type Cluster_RunAndWait_Call struct {
	*mock.Call
}

// RunAndWait is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *types.DeployOptions
//   - inCh <-chan []byte
func (_e *Cluster_Expecter) RunAndWait(ctx any, opts any, inCh any) *Cluster_RunAndWait_Call {
	return &Cluster_RunAndWait_Call{Call: _e.mock.On("RunAndWait", ctx, opts, inCh)}
}

func (_c *Cluster_RunAndWait_Call) Run(run func(ctx context.Context, opts *types.DeployOptions, inCh <-chan []byte)) *Cluster_RunAndWait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.DeployOptions
		if args[1] != nil {
			arg1 = args[1].(*types.DeployOptions)
		}
		var arg2 <-chan []byte
		if args[2] != nil {
			arg2 = args[2].(<-chan []byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Cluster_RunAndWait_Call) Return(strings []string, attachWorkloadMessageCh <-chan *types.AttachWorkloadMessage, err error) *Cluster_RunAndWait_Call {
	_c.Call.Return(strings, attachWorkloadMessageCh, err)
	return _c
}

func (_c *Cluster_RunAndWait_Call) RunAndReturn(run func(ctx context.Context, opts *types.DeployOptions, inCh <-chan []byte) ([]string, <-chan *types.AttachWorkloadMessage, error)) *Cluster_RunAndWait_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function for the type Cluster
func (_mock *Cluster) Send(ctx context.Context, opts *types.SendOptions) (chan *types.SendMessage, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 chan *types.SendMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.SendOptions) (chan *types.SendMessage, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.SendOptions) chan *types.SendMessage); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan *types.SendMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types.SendOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cluster_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type Cluster_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *types.SendOptions
func (_e *Cluster_Expecter) Send(ctx any, opts any) *Cluster_Send_Call {
	return &Cluster_Send_Call{Call: _e.mock.On("Send", ctx, opts)}
}

func (_c *Cluster_Send_Call) Run(run func(ctx context.Context, opts *types.SendOptions)) *Cluster_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.SendOptions
		if args[1] != nil {
			arg1 = args[1].(*types.SendOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cluster_Send_Call) Return(sendMessageCh chan *types.SendMessage, err error) *Cluster_Send_Call {
	_c.Call.Return(sendMessageCh, err)
	return _c
}

func (_c *Cluster_Send_Call) RunAndReturn(run func(ctx context.Context, opts *types.SendOptions) (chan *types.SendMessage, error)) *Cluster_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendLargeFile provides a mock function for the type Cluster
func (_mock *Cluster) SendLargeFile(ctx context.Context, opts chan *types.SendLargeFileOptions) chan *types.SendMessage {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for SendLargeFile")
	}

	var r0 chan *types.SendMessage
	if returnFunc, ok := ret.Get(0).(func(context.Context, chan *types.SendLargeFileOptions) chan *types.SendMessage); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan *types.SendMessage)
		}
	}
	return r0
}

// Cluster_SendLargeFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendLargeFile'
type Cluster_SendLargeFile_Call struct {
	*mock.Call
}

// SendLargeFile is a helper method to define mock.On call
//   - ctx context.Context
//   - opts chan *types.SendLargeFileOptions
func (_e *Cluster_Expecter) SendLargeFile(ctx any, opts any) *Cluster_SendLargeFile_Call {
	return &Cluster_SendLargeFile_Call{Call: _e.mock.On("SendLargeFile", ctx, opts)}
}

func (_c *Cluster_SendLargeFile_Call) Run(run func(ctx context.Context, opts chan *types.SendLargeFileOptions)) *Cluster_SendLargeFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 chan *types.SendLargeFileOptions
		if args[1] != nil {
			arg1 = args[1].(chan *types.SendLargeFileOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cluster_SendLargeFile_Call) Return(sendMessageCh chan *types.SendMessage) *Cluster_SendLargeFile_Call {
	_c.Call.Return(sendMessageCh)
	return _c
}

func (_c *Cluster_SendLargeFile_Call) RunAndReturn(run func(ctx context.Context, opts chan *types.SendLargeFileOptions) chan *types.SendMessage) *Cluster_SendLargeFile_Call {
	_c.Call.Return(run)
	return _c
}

// SetNode provides a mock function for the type Cluster
func (_mock *Cluster) SetNode(ctx context.Context, opts *types.SetNodeOptions) (*types.Node, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for SetNode")
	}

	var r0 *types.Node
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.SetNodeOptions) (*types.Node, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.SetNodeOptions) *types.Node); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Node)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types.SetNodeOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cluster_SetNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNode'
type Cluster_SetNode_Call struct {
	*mock.Call
}

// SetNode is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *types.SetNodeOptions
func (_e *Cluster_Expecter) SetNode(ctx any, opts any) *Cluster_SetNode_Call {
	return &Cluster_SetNode_Call{Call: _e.mock.On("SetNode", ctx, opts)}
}

func (_c *Cluster_SetNode_Call) Run(run func(ctx context.Context, opts *types.SetNodeOptions)) *Cluster_SetNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.SetNodeOptions
		if args[1] != nil {
			arg1 = args[1].(*types.SetNodeOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cluster_SetNode_Call) Return(node *types.Node, err error) *Cluster_SetNode_Call {
	_c.Call.Return(node, err)
	return _c
}

func (_c *Cluster_SetNode_Call) RunAndReturn(run func(ctx context.Context, opts *types.SetNodeOptions) (*types.Node, error)) *Cluster_SetNode_Call {
	_c.Call.Return(run)
	return _c
}

// SetNodeStatus provides a mock function for the type Cluster
func (_mock *Cluster) SetNodeStatus(ctx context.Context, nodename string, ttl int64) error {
	ret := _mock.Called(ctx, nodename, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetNodeStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = returnFunc(ctx, nodename, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Cluster_SetNodeStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNodeStatus'
type Cluster_SetNodeStatus_Call struct {
	*mock.Call
}

// SetNodeStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - nodename string
//   - ttl int64
func (_e *Cluster_Expecter) SetNodeStatus(ctx any, nodename any, ttl any) *Cluster_SetNodeStatus_Call {
	return &Cluster_SetNodeStatus_Call{Call: _e.mock.On("SetNodeStatus", ctx, nodename, ttl)}
}

func (_c *Cluster_SetNodeStatus_Call) Run(run func(ctx context.Context, nodename string, ttl int64)) *Cluster_SetNodeStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Cluster_SetNodeStatus_Call) Return(err error) *Cluster_SetNodeStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Cluster_SetNodeStatus_Call) RunAndReturn(run func(ctx context.Context, nodename string, ttl int64) error) *Cluster_SetNodeStatus_Call {
	_c.Call.Return(run)
	return _c
}

// SetWorkloadsStatus provides a mock function for the type Cluster
func (_mock *Cluster) SetWorkloadsStatus(ctx context.Context, status []*types.StatusMeta, ttls map[string]int64) ([]*types.StatusMeta, error) {
	ret := _mock.Called(ctx, status, ttls)

	if len(ret) == 0 {
		panic("no return value specified for SetWorkloadsStatus")
	}

	var r0 []*types.StatusMeta
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*types.StatusMeta, map[string]int64) ([]*types.StatusMeta, error)); ok {
		return returnFunc(ctx, status, ttls)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*types.StatusMeta, map[string]int64) []*types.StatusMeta); ok {
		r0 = returnFunc(ctx, status, ttls)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.StatusMeta)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []*types.StatusMeta, map[string]int64) error); ok {
		r1 = returnFunc(ctx, status, ttls)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cluster_SetWorkloadsStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWorkloadsStatus'
type Cluster_SetWorkloadsStatus_Call struct {
	*mock.Call
}

// SetWorkloadsStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - status []*types.StatusMeta
//   - ttls map[string]int64
func (_e *Cluster_Expecter) SetWorkloadsStatus(ctx any, status any, ttls any) *Cluster_SetWorkloadsStatus_Call {
	return &Cluster_SetWorkloadsStatus_Call{Call: _e.mock.On("SetWorkloadsStatus", ctx, status, ttls)}
}

func (_c *Cluster_SetWorkloadsStatus_Call) Run(run func(ctx context.Context, status []*types.StatusMeta, ttls map[string]int64)) *Cluster_SetWorkloadsStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*types.StatusMeta
		if args[1] != nil {
			arg1 = args[1].([]*types.StatusMeta)
		}
		var arg2 map[string]int64
		if args[2] != nil {
			arg2 = args[2].(map[string]int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Cluster_SetWorkloadsStatus_Call) Return(statusMetas []*types.StatusMeta, err error) *Cluster_SetWorkloadsStatus_Call {
	_c.Call.Return(statusMetas, err)
	return _c
}

func (_c *Cluster_SetWorkloadsStatus_Call) RunAndReturn(run func(ctx context.Context, status []*types.StatusMeta, ttls map[string]int64) ([]*types.StatusMeta, error)) *Cluster_SetWorkloadsStatus_Call {
	_c.Call.Return(run)
	return _c
}

// WatchServiceStatus provides a mock function for the type Cluster
func (_mock *Cluster) WatchServiceStatus(context1 context.Context) (<-chan types.ServiceStatus, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for WatchServiceStatus")
	}

	var r0 <-chan types.ServiceStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (<-chan types.ServiceStatus, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) <-chan types.ServiceStatus); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan types.ServiceStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cluster_WatchServiceStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WatchServiceStatus'
type Cluster_WatchServiceStatus_Call struct {
	*mock.Call
}

// WatchServiceStatus is a helper method to define mock.On call
//   - context1 context.Context
func (_e *Cluster_Expecter) WatchServiceStatus(context1 any) *Cluster_WatchServiceStatus_Call {
	return &Cluster_WatchServiceStatus_Call{Call: _e.mock.On("WatchServiceStatus", context1)}
}

func (_c *Cluster_WatchServiceStatus_Call) Run(run func(context1 context.Context)) *Cluster_WatchServiceStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Cluster_WatchServiceStatus_Call) Return(serviceStatusCh <-chan types.ServiceStatus, err error) *Cluster_WatchServiceStatus_Call {
	_c.Call.Return(serviceStatusCh, err)
	return _c
}

func (_c *Cluster_WatchServiceStatus_Call) RunAndReturn(run func(context1 context.Context) (<-chan types.ServiceStatus, error)) *Cluster_WatchServiceStatus_Call {
	_c.Call.Return(run)
	return _c
}

// WorkloadStatusStream provides a mock function for the type Cluster
func (_mock *Cluster) WorkloadStatusStream(ctx context.Context, appname string, entrypoint string, nodename string, labels map[string]string) chan *types.WorkloadStatus {
	ret := _mock.Called(ctx, appname, entrypoint, nodename, labels)

	if len(ret) == 0 {
		panic("no return value specified for WorkloadStatusStream")
	}

	var r0 chan *types.WorkloadStatus
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, map[string]string) chan *types.WorkloadStatus); ok {
		r0 = returnFunc(ctx, appname, entrypoint, nodename, labels)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan *types.WorkloadStatus)
		}
	}
	return r0
}

// Cluster_WorkloadStatusStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WorkloadStatusStream'
type Cluster_WorkloadStatusStream_Call struct {
	*mock.Call
}

// WorkloadStatusStream is a helper method to define mock.On call
//   - ctx context.Context
//   - appname string
//   - entrypoint string
//   - nodename string
//   - labels map[string]string
func (_e *Cluster_Expecter) WorkloadStatusStream(ctx any, appname any, entrypoint any, nodename any, labels any) *Cluster_WorkloadStatusStream_Call {
	return &Cluster_WorkloadStatusStream_Call{Call: _e.mock.On("WorkloadStatusStream", ctx, appname, entrypoint, nodename, labels)}
}

func (_c *Cluster_WorkloadStatusStream_Call) Run(run func(ctx context.Context, appname string, entrypoint string, nodename string, labels map[string]string)) *Cluster_WorkloadStatusStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 map[string]string
		if args[4] != nil {
			arg4 = args[4].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *Cluster_WorkloadStatusStream_Call) Return(workloadStatusCh chan *types.WorkloadStatus) *Cluster_WorkloadStatusStream_Call {
	_c.Call.Return(workloadStatusCh)
	return _c
}

func (_c *Cluster_WorkloadStatusStream_Call) RunAndReturn(run func(ctx context.Context, appname string, entrypoint string, nodename string, labels map[string]string) chan *types.WorkloadStatus) *Cluster_WorkloadStatusStream_Call {
	_c.Call.Return(run)
	return _c
}
