// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	clientv3 "go.etcd.io/etcd/client/v3"
)

// NewETCDClientV3 creates a new instance of ETCDClientV3. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewETCDClientV3(t interface {
	mock.TestingT
	Cleanup(func())
}) *ETCDClientV3 {
	mock := &ETCDClientV3{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ETCDClientV3 is an autogenerated mock type for the ETCDClientV3 type
type ETCDClientV3 struct {
	mock.Mock
}

type ETCDClientV3_Expecter struct {
	mock *mock.Mock
}

func (_m *ETCDClientV3) EXPECT() *ETCDClientV3_Expecter {
	return &ETCDClientV3_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type ETCDClientV3
func (_mock *ETCDClientV3) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ETCDClientV3_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type ETCDClientV3_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *ETCDClientV3_Expecter) Close() *ETCDClientV3_Close_Call {
	return &ETCDClientV3_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *ETCDClientV3_Close_Call) Run(run func()) *ETCDClientV3_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ETCDClientV3_Close_Call) Return(err error) *ETCDClientV3_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ETCDClientV3_Close_Call) RunAndReturn(run func() error) *ETCDClientV3_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Compact provides a mock function for the type ETCDClientV3
func (_mock *ETCDClientV3) Compact(ctx context.Context, rev int64, opts ...clientv3.CompactOption) (*clientv3.CompactResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, rev, opts)
	} else {
		tmpRet = _mock.Called(ctx, rev)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Compact")
	}

	var r0 *clientv3.CompactResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, ...clientv3.CompactOption) (*clientv3.CompactResponse, error)); ok {
		return returnFunc(ctx, rev, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, ...clientv3.CompactOption) *clientv3.CompactResponse); ok {
		r0 = returnFunc(ctx, rev, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clientv3.CompactResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, ...clientv3.CompactOption) error); ok {
		r1 = returnFunc(ctx, rev, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ETCDClientV3_Compact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compact'
type ETCDClientV3_Compact_Call struct {
	*mock.Call
}

// Compact is a helper method to define mock.On call
//   - ctx context.Context
//   - rev int64
//   - opts ...clientv3.CompactOption
func (_e *ETCDClientV3_Expecter) Compact(ctx any, rev any, opts ...any) *ETCDClientV3_Compact_Call {
	return &ETCDClientV3_Compact_Call{Call: _e.mock.On("Compact",
		append([]any{ctx, rev}, opts...)...)}
}

func (_c *ETCDClientV3_Compact_Call) Run(run func(ctx context.Context, rev int64, opts ...clientv3.CompactOption)) *ETCDClientV3_Compact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 []clientv3.CompactOption
		var variadicArgs []clientv3.CompactOption
		if len(args) > 2 {
			variadicArgs = args[2].([]clientv3.CompactOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *ETCDClientV3_Compact_Call) Return(compactResponse *clientv3.CompactResponse, err error) *ETCDClientV3_Compact_Call {
	_c.Call.Return(compactResponse, err)
	return _c
}

func (_c *ETCDClientV3_Compact_Call) RunAndReturn(run func(ctx context.Context, rev int64, opts ...clientv3.CompactOption) (*clientv3.CompactResponse, error)) *ETCDClientV3_Compact_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type ETCDClientV3
func (_mock *ETCDClientV3) Delete(ctx context.Context, key string, opts ...clientv3.OpOption) (*clientv3.DeleteResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, key, opts)
	} else {
		tmpRet = _mock.Called(ctx, key)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *clientv3.DeleteResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...clientv3.OpOption) (*clientv3.DeleteResponse, error)); ok {
		return returnFunc(ctx, key, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...clientv3.OpOption) *clientv3.DeleteResponse); ok {
		r0 = returnFunc(ctx, key, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clientv3.DeleteResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...clientv3.OpOption) error); ok {
		r1 = returnFunc(ctx, key, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ETCDClientV3_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ETCDClientV3_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - opts ...clientv3.OpOption
func (_e *ETCDClientV3_Expecter) Delete(ctx any, key any, opts ...any) *ETCDClientV3_Delete_Call {
	return &ETCDClientV3_Delete_Call{Call: _e.mock.On("Delete",
		append([]any{ctx, key}, opts...)...)}
}

func (_c *ETCDClientV3_Delete_Call) Run(run func(ctx context.Context, key string, opts ...clientv3.OpOption)) *ETCDClientV3_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []clientv3.OpOption
		var variadicArgs []clientv3.OpOption
		if len(args) > 2 {
			variadicArgs = args[2].([]clientv3.OpOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *ETCDClientV3_Delete_Call) Return(deleteResponse *clientv3.DeleteResponse, err error) *ETCDClientV3_Delete_Call {
	_c.Call.Return(deleteResponse, err)
	return _c
}

func (_c *ETCDClientV3_Delete_Call) RunAndReturn(run func(ctx context.Context, key string, opts ...clientv3.OpOption) (*clientv3.DeleteResponse, error)) *ETCDClientV3_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Do provides a mock function for the type ETCDClientV3
func (_mock *ETCDClientV3) Do(ctx context.Context, op clientv3.Op) (clientv3.OpResponse, error) {
	ret := _mock.Called(ctx, op)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 clientv3.OpResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, clientv3.Op) (clientv3.OpResponse, error)); ok {
		return returnFunc(ctx, op)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, clientv3.Op) clientv3.OpResponse); ok {
		r0 = returnFunc(ctx, op)
	} else {
		r0 = ret.Get(0).(clientv3.OpResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, clientv3.Op) error); ok {
		r1 = returnFunc(ctx, op)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ETCDClientV3_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type ETCDClientV3_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - ctx context.Context
//   - op clientv3.Op
func (_e *ETCDClientV3_Expecter) Do(ctx any, op any) *ETCDClientV3_Do_Call {
	return &ETCDClientV3_Do_Call{Call: _e.mock.On("Do", ctx, op)}
}

func (_c *ETCDClientV3_Do_Call) Run(run func(ctx context.Context, op clientv3.Op)) *ETCDClientV3_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 clientv3.Op
		if args[1] != nil {
			arg1 = args[1].(clientv3.Op)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ETCDClientV3_Do_Call) Return(opResponse clientv3.OpResponse, err error) *ETCDClientV3_Do_Call {
	_c.Call.Return(opResponse, err)
	return _c
}

func (_c *ETCDClientV3_Do_Call) RunAndReturn(run func(ctx context.Context, op clientv3.Op) (clientv3.OpResponse, error)) *ETCDClientV3_Do_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type ETCDClientV3
func (_mock *ETCDClientV3) Get(ctx context.Context, key string, opts ...clientv3.OpOption) (*clientv3.GetResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, key, opts)
	} else {
		tmpRet = _mock.Called(ctx, key)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *clientv3.GetResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...clientv3.OpOption) (*clientv3.GetResponse, error)); ok {
		return returnFunc(ctx, key, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...clientv3.OpOption) *clientv3.GetResponse); ok {
		r0 = returnFunc(ctx, key, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clientv3.GetResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...clientv3.OpOption) error); ok {
		r1 = returnFunc(ctx, key, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ETCDClientV3_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ETCDClientV3_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - opts ...clientv3.OpOption
func (_e *ETCDClientV3_Expecter) Get(ctx any, key any, opts ...any) *ETCDClientV3_Get_Call {
	return &ETCDClientV3_Get_Call{Call: _e.mock.On("Get",
		append([]any{ctx, key}, opts...)...)}
}

func (_c *ETCDClientV3_Get_Call) Run(run func(ctx context.Context, key string, opts ...clientv3.OpOption)) *ETCDClientV3_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []clientv3.OpOption
		var variadicArgs []clientv3.OpOption
		if len(args) > 2 {
			variadicArgs = args[2].([]clientv3.OpOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *ETCDClientV3_Get_Call) Return(getResponse *clientv3.GetResponse, err error) *ETCDClientV3_Get_Call {
	_c.Call.Return(getResponse, err)
	return _c
}

func (_c *ETCDClientV3_Get_Call) RunAndReturn(run func(ctx context.Context, key string, opts ...clientv3.OpOption) (*clientv3.GetResponse, error)) *ETCDClientV3_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetStream provides a mock function for the type ETCDClientV3
func (_mock *ETCDClientV3) GetStream(ctx context.Context, key string, opts ...clientv3.OpOption) (clientv3.GetStreamChan, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, key, opts)
	} else {
		tmpRet = _mock.Called(ctx, key)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetStream")
	}

	var r0 clientv3.GetStreamChan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...clientv3.OpOption) (clientv3.GetStreamChan, error)); ok {
		return returnFunc(ctx, key, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...clientv3.OpOption) clientv3.GetStreamChan); ok {
		r0 = returnFunc(ctx, key, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(clientv3.GetStreamChan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...clientv3.OpOption) error); ok {
		r1 = returnFunc(ctx, key, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ETCDClientV3_GetStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStream'
type ETCDClientV3_GetStream_Call struct {
	*mock.Call
}

// GetStream is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - opts ...clientv3.OpOption
func (_e *ETCDClientV3_Expecter) GetStream(ctx any, key any, opts ...any) *ETCDClientV3_GetStream_Call {
	return &ETCDClientV3_GetStream_Call{Call: _e.mock.On("GetStream",
		append([]any{ctx, key}, opts...)...)}
}

func (_c *ETCDClientV3_GetStream_Call) Run(run func(ctx context.Context, key string, opts ...clientv3.OpOption)) *ETCDClientV3_GetStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []clientv3.OpOption
		var variadicArgs []clientv3.OpOption
		if len(args) > 2 {
			variadicArgs = args[2].([]clientv3.OpOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *ETCDClientV3_GetStream_Call) Return(getStreamChan clientv3.GetStreamChan, err error) *ETCDClientV3_GetStream_Call {
	_c.Call.Return(getStreamChan, err)
	return _c
}

func (_c *ETCDClientV3_GetStream_Call) RunAndReturn(run func(ctx context.Context, key string, opts ...clientv3.OpOption) (clientv3.GetStreamChan, error)) *ETCDClientV3_GetStream_Call {
	_c.Call.Return(run)
	return _c
}

// Grant provides a mock function for the type ETCDClientV3
func (_mock *ETCDClientV3) Grant(ctx context.Context, ttl int64) (*clientv3.LeaseGrantResponse, error) {
	ret := _mock.Called(ctx, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Grant")
	}

	var r0 *clientv3.LeaseGrantResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*clientv3.LeaseGrantResponse, error)); ok {
		return returnFunc(ctx, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *clientv3.LeaseGrantResponse); ok {
		r0 = returnFunc(ctx, ttl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clientv3.LeaseGrantResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ETCDClientV3_Grant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Grant'
type ETCDClientV3_Grant_Call struct {
	*mock.Call
}

// Grant is a helper method to define mock.On call
//   - ctx context.Context
//   - ttl int64
func (_e *ETCDClientV3_Expecter) Grant(ctx any, ttl any) *ETCDClientV3_Grant_Call {
	return &ETCDClientV3_Grant_Call{Call: _e.mock.On("Grant", ctx, ttl)}
}

func (_c *ETCDClientV3_Grant_Call) Run(run func(ctx context.Context, ttl int64)) *ETCDClientV3_Grant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ETCDClientV3_Grant_Call) Return(leaseGrantResponse *clientv3.LeaseGrantResponse, err error) *ETCDClientV3_Grant_Call {
	_c.Call.Return(leaseGrantResponse, err)
	return _c
}

func (_c *ETCDClientV3_Grant_Call) RunAndReturn(run func(ctx context.Context, ttl int64) (*clientv3.LeaseGrantResponse, error)) *ETCDClientV3_Grant_Call {
	_c.Call.Return(run)
	return _c
}

// KeepAlive provides a mock function for the type ETCDClientV3
func (_mock *ETCDClientV3) KeepAlive(ctx context.Context, id clientv3.LeaseID) (<-chan *clientv3.LeaseKeepAliveResponse, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for KeepAlive")
	}

	var r0 <-chan *clientv3.LeaseKeepAliveResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, clientv3.LeaseID) (<-chan *clientv3.LeaseKeepAliveResponse, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, clientv3.LeaseID) <-chan *clientv3.LeaseKeepAliveResponse); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *clientv3.LeaseKeepAliveResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, clientv3.LeaseID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ETCDClientV3_KeepAlive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KeepAlive'
type ETCDClientV3_KeepAlive_Call struct {
	*mock.Call
}

// KeepAlive is a helper method to define mock.On call
//   - ctx context.Context
//   - id clientv3.LeaseID
func (_e *ETCDClientV3_Expecter) KeepAlive(ctx any, id any) *ETCDClientV3_KeepAlive_Call {
	return &ETCDClientV3_KeepAlive_Call{Call: _e.mock.On("KeepAlive", ctx, id)}
}

func (_c *ETCDClientV3_KeepAlive_Call) Run(run func(ctx context.Context, id clientv3.LeaseID)) *ETCDClientV3_KeepAlive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 clientv3.LeaseID
		if args[1] != nil {
			arg1 = args[1].(clientv3.LeaseID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ETCDClientV3_KeepAlive_Call) Return(leaseKeepAliveResponseCh <-chan *clientv3.LeaseKeepAliveResponse, err error) *ETCDClientV3_KeepAlive_Call {
	_c.Call.Return(leaseKeepAliveResponseCh, err)
	return _c
}

func (_c *ETCDClientV3_KeepAlive_Call) RunAndReturn(run func(ctx context.Context, id clientv3.LeaseID) (<-chan *clientv3.LeaseKeepAliveResponse, error)) *ETCDClientV3_KeepAlive_Call {
	_c.Call.Return(run)
	return _c
}

// KeepAliveOnce provides a mock function for the type ETCDClientV3
func (_mock *ETCDClientV3) KeepAliveOnce(ctx context.Context, id clientv3.LeaseID) (*clientv3.LeaseKeepAliveResponse, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for KeepAliveOnce")
	}

	var r0 *clientv3.LeaseKeepAliveResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, clientv3.LeaseID) (*clientv3.LeaseKeepAliveResponse, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, clientv3.LeaseID) *clientv3.LeaseKeepAliveResponse); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clientv3.LeaseKeepAliveResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, clientv3.LeaseID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ETCDClientV3_KeepAliveOnce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KeepAliveOnce'
type ETCDClientV3_KeepAliveOnce_Call struct {
	*mock.Call
}

// KeepAliveOnce is a helper method to define mock.On call
//   - ctx context.Context
//   - id clientv3.LeaseID
func (_e *ETCDClientV3_Expecter) KeepAliveOnce(ctx any, id any) *ETCDClientV3_KeepAliveOnce_Call {
	return &ETCDClientV3_KeepAliveOnce_Call{Call: _e.mock.On("KeepAliveOnce", ctx, id)}
}

func (_c *ETCDClientV3_KeepAliveOnce_Call) Run(run func(ctx context.Context, id clientv3.LeaseID)) *ETCDClientV3_KeepAliveOnce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 clientv3.LeaseID
		if args[1] != nil {
			arg1 = args[1].(clientv3.LeaseID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ETCDClientV3_KeepAliveOnce_Call) Return(leaseKeepAliveResponse *clientv3.LeaseKeepAliveResponse, err error) *ETCDClientV3_KeepAliveOnce_Call {
	_c.Call.Return(leaseKeepAliveResponse, err)
	return _c
}

func (_c *ETCDClientV3_KeepAliveOnce_Call) RunAndReturn(run func(ctx context.Context, id clientv3.LeaseID) (*clientv3.LeaseKeepAliveResponse, error)) *ETCDClientV3_KeepAliveOnce_Call {
	_c.Call.Return(run)
	return _c
}

// Leases provides a mock function for the type ETCDClientV3
func (_mock *ETCDClientV3) Leases(ctx context.Context) (*clientv3.LeaseLeasesResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Leases")
	}

	var r0 *clientv3.LeaseLeasesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*clientv3.LeaseLeasesResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *clientv3.LeaseLeasesResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clientv3.LeaseLeasesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ETCDClientV3_Leases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Leases'
type ETCDClientV3_Leases_Call struct {
	*mock.Call
}

// Leases is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ETCDClientV3_Expecter) Leases(ctx any) *ETCDClientV3_Leases_Call {
	return &ETCDClientV3_Leases_Call{Call: _e.mock.On("Leases", ctx)}
}

func (_c *ETCDClientV3_Leases_Call) Run(run func(ctx context.Context)) *ETCDClientV3_Leases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ETCDClientV3_Leases_Call) Return(leaseLeasesResponse *clientv3.LeaseLeasesResponse, err error) *ETCDClientV3_Leases_Call {
	_c.Call.Return(leaseLeasesResponse, err)
	return _c
}

func (_c *ETCDClientV3_Leases_Call) RunAndReturn(run func(ctx context.Context) (*clientv3.LeaseLeasesResponse, error)) *ETCDClientV3_Leases_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type ETCDClientV3
func (_mock *ETCDClientV3) Put(ctx context.Context, key string, val string, opts ...clientv3.OpOption) (*clientv3.PutResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, key, val, opts)
	} else {
		tmpRet = _mock.Called(ctx, key, val)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 *clientv3.PutResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...clientv3.OpOption) (*clientv3.PutResponse, error)); ok {
		return returnFunc(ctx, key, val, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...clientv3.OpOption) *clientv3.PutResponse); ok {
		r0 = returnFunc(ctx, key, val, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clientv3.PutResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, ...clientv3.OpOption) error); ok {
		r1 = returnFunc(ctx, key, val, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ETCDClientV3_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type ETCDClientV3_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - val string
//   - opts ...clientv3.OpOption
func (_e *ETCDClientV3_Expecter) Put(ctx any, key any, val any, opts ...any) *ETCDClientV3_Put_Call {
	return &ETCDClientV3_Put_Call{Call: _e.mock.On("Put",
		append([]any{ctx, key, val}, opts...)...)}
}

func (_c *ETCDClientV3_Put_Call) Run(run func(ctx context.Context, key string, val string, opts ...clientv3.OpOption)) *ETCDClientV3_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []clientv3.OpOption
		var variadicArgs []clientv3.OpOption
		if len(args) > 3 {
			variadicArgs = args[3].([]clientv3.OpOption)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *ETCDClientV3_Put_Call) Return(putResponse *clientv3.PutResponse, err error) *ETCDClientV3_Put_Call {
	_c.Call.Return(putResponse, err)
	return _c
}

func (_c *ETCDClientV3_Put_Call) RunAndReturn(run func(ctx context.Context, key string, val string, opts ...clientv3.OpOption) (*clientv3.PutResponse, error)) *ETCDClientV3_Put_Call {
	_c.Call.Return(run)
	return _c
}

// RequestProgress provides a mock function for the type ETCDClientV3
func (_mock *ETCDClientV3) RequestProgress(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RequestProgress")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ETCDClientV3_RequestProgress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestProgress'
type ETCDClientV3_RequestProgress_Call struct {
	*mock.Call
}

// RequestProgress is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ETCDClientV3_Expecter) RequestProgress(ctx any) *ETCDClientV3_RequestProgress_Call {
	return &ETCDClientV3_RequestProgress_Call{Call: _e.mock.On("RequestProgress", ctx)}
}

func (_c *ETCDClientV3_RequestProgress_Call) Run(run func(ctx context.Context)) *ETCDClientV3_RequestProgress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ETCDClientV3_RequestProgress_Call) Return(err error) *ETCDClientV3_RequestProgress_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ETCDClientV3_RequestProgress_Call) RunAndReturn(run func(ctx context.Context) error) *ETCDClientV3_RequestProgress_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function for the type ETCDClientV3
func (_mock *ETCDClientV3) Revoke(ctx context.Context, id clientv3.LeaseID) (*clientv3.LeaseRevokeResponse, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 *clientv3.LeaseRevokeResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, clientv3.LeaseID) (*clientv3.LeaseRevokeResponse, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, clientv3.LeaseID) *clientv3.LeaseRevokeResponse); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clientv3.LeaseRevokeResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, clientv3.LeaseID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ETCDClientV3_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type ETCDClientV3_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - id clientv3.LeaseID
func (_e *ETCDClientV3_Expecter) Revoke(ctx any, id any) *ETCDClientV3_Revoke_Call {
	return &ETCDClientV3_Revoke_Call{Call: _e.mock.On("Revoke", ctx, id)}
}

func (_c *ETCDClientV3_Revoke_Call) Run(run func(ctx context.Context, id clientv3.LeaseID)) *ETCDClientV3_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 clientv3.LeaseID
		if args[1] != nil {
			arg1 = args[1].(clientv3.LeaseID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ETCDClientV3_Revoke_Call) Return(leaseRevokeResponse *clientv3.LeaseRevokeResponse, err error) *ETCDClientV3_Revoke_Call {
	_c.Call.Return(leaseRevokeResponse, err)
	return _c
}

func (_c *ETCDClientV3_Revoke_Call) RunAndReturn(run func(ctx context.Context, id clientv3.LeaseID) (*clientv3.LeaseRevokeResponse, error)) *ETCDClientV3_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// TimeToLive provides a mock function for the type ETCDClientV3
func (_mock *ETCDClientV3) TimeToLive(ctx context.Context, id clientv3.LeaseID, opts ...clientv3.LeaseOption) (*clientv3.LeaseTimeToLiveResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, id, opts)
	} else {
		tmpRet = _mock.Called(ctx, id)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for TimeToLive")
	}

	var r0 *clientv3.LeaseTimeToLiveResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, clientv3.LeaseID, ...clientv3.LeaseOption) (*clientv3.LeaseTimeToLiveResponse, error)); ok {
		return returnFunc(ctx, id, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, clientv3.LeaseID, ...clientv3.LeaseOption) *clientv3.LeaseTimeToLiveResponse); ok {
		r0 = returnFunc(ctx, id, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clientv3.LeaseTimeToLiveResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, clientv3.LeaseID, ...clientv3.LeaseOption) error); ok {
		r1 = returnFunc(ctx, id, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ETCDClientV3_TimeToLive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TimeToLive'
type ETCDClientV3_TimeToLive_Call struct {
	*mock.Call
}

// TimeToLive is a helper method to define mock.On call
//   - ctx context.Context
//   - id clientv3.LeaseID
//   - opts ...clientv3.LeaseOption
func (_e *ETCDClientV3_Expecter) TimeToLive(ctx any, id any, opts ...any) *ETCDClientV3_TimeToLive_Call {
	return &ETCDClientV3_TimeToLive_Call{Call: _e.mock.On("TimeToLive",
		append([]any{ctx, id}, opts...)...)}
}

func (_c *ETCDClientV3_TimeToLive_Call) Run(run func(ctx context.Context, id clientv3.LeaseID, opts ...clientv3.LeaseOption)) *ETCDClientV3_TimeToLive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 clientv3.LeaseID
		if args[1] != nil {
			arg1 = args[1].(clientv3.LeaseID)
		}
		var arg2 []clientv3.LeaseOption
		var variadicArgs []clientv3.LeaseOption
		if len(args) > 2 {
			variadicArgs = args[2].([]clientv3.LeaseOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *ETCDClientV3_TimeToLive_Call) Return(leaseTimeToLiveResponse *clientv3.LeaseTimeToLiveResponse, err error) *ETCDClientV3_TimeToLive_Call {
	_c.Call.Return(leaseTimeToLiveResponse, err)
	return _c
}

func (_c *ETCDClientV3_TimeToLive_Call) RunAndReturn(run func(ctx context.Context, id clientv3.LeaseID, opts ...clientv3.LeaseOption) (*clientv3.LeaseTimeToLiveResponse, error)) *ETCDClientV3_TimeToLive_Call {
	_c.Call.Return(run)
	return _c
}

// Txn provides a mock function for the type ETCDClientV3
func (_mock *ETCDClientV3) Txn(ctx context.Context) clientv3.Txn {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Txn")
	}

	var r0 clientv3.Txn
	if returnFunc, ok := ret.Get(0).(func(context.Context) clientv3.Txn); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(clientv3.Txn)
		}
	}
	return r0
}

// ETCDClientV3_Txn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Txn'
type ETCDClientV3_Txn_Call struct {
	*mock.Call
}

// Txn is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ETCDClientV3_Expecter) Txn(ctx any) *ETCDClientV3_Txn_Call {
	return &ETCDClientV3_Txn_Call{Call: _e.mock.On("Txn", ctx)}
}

func (_c *ETCDClientV3_Txn_Call) Run(run func(ctx context.Context)) *ETCDClientV3_Txn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ETCDClientV3_Txn_Call) Return(txn clientv3.Txn) *ETCDClientV3_Txn_Call {
	_c.Call.Return(txn)
	return _c
}

func (_c *ETCDClientV3_Txn_Call) RunAndReturn(run func(ctx context.Context) clientv3.Txn) *ETCDClientV3_Txn_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function for the type ETCDClientV3
func (_mock *ETCDClientV3) Watch(ctx context.Context, key string, opts ...clientv3.OpOption) clientv3.WatchChan {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, key, opts)
	} else {
		tmpRet = _mock.Called(ctx, key)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 clientv3.WatchChan
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...clientv3.OpOption) clientv3.WatchChan); ok {
		r0 = returnFunc(ctx, key, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(clientv3.WatchChan)
		}
	}
	return r0
}

// ETCDClientV3_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type ETCDClientV3_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - opts ...clientv3.OpOption
func (_e *ETCDClientV3_Expecter) Watch(ctx any, key any, opts ...any) *ETCDClientV3_Watch_Call {
	return &ETCDClientV3_Watch_Call{Call: _e.mock.On("Watch",
		append([]any{ctx, key}, opts...)...)}
}

func (_c *ETCDClientV3_Watch_Call) Run(run func(ctx context.Context, key string, opts ...clientv3.OpOption)) *ETCDClientV3_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []clientv3.OpOption
		var variadicArgs []clientv3.OpOption
		if len(args) > 2 {
			variadicArgs = args[2].([]clientv3.OpOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *ETCDClientV3_Watch_Call) Return(watchChan clientv3.WatchChan) *ETCDClientV3_Watch_Call {
	_c.Call.Return(watchChan)
	return _c
}

func (_c *ETCDClientV3_Watch_Call) RunAndReturn(run func(ctx context.Context, key string, opts ...clientv3.OpOption) clientv3.WatchChan) *ETCDClientV3_Watch_Call {
	_c.Call.Return(run)
	return _c
}
