// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/projecteru2/core/lock"
	mock "github.com/stretchr/testify/mock"
	"go.etcd.io/etcd/api/v3/mvccpb"
	"go.etcd.io/etcd/client/v3"
)

// NewKV creates a new instance of KV. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKV(t interface {
	mock.TestingT
	Cleanup(func())
}) *KV {
	mock := &KV{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// KV is an autogenerated mock type for the KV type
type KV struct {
	mock.Mock
}

type KV_Expecter struct {
	mock *mock.Mock
}

func (_m *KV) EXPECT() *KV_Expecter {
	return &KV_Expecter{mock: &_m.Mock}
}

// BatchCreate provides a mock function for the type KV
func (_mock *KV) BatchCreate(ctx context.Context, data map[string]string, opts ...clientv3.OpOption) (*clientv3.TxnResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, data, opts)
	} else {
		tmpRet = _mock.Called(ctx, data)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for BatchCreate")
	}

	var r0 *clientv3.TxnResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]string, ...clientv3.OpOption) (*clientv3.TxnResponse, error)); ok {
		return returnFunc(ctx, data, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]string, ...clientv3.OpOption) *clientv3.TxnResponse); ok {
		r0 = returnFunc(ctx, data, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clientv3.TxnResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, map[string]string, ...clientv3.OpOption) error); ok {
		r1 = returnFunc(ctx, data, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KV_BatchCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchCreate'
type KV_BatchCreate_Call struct {
	*mock.Call
}

// BatchCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - data map[string]string
//   - opts ...clientv3.OpOption
func (_e *KV_Expecter) BatchCreate(ctx any, data any, opts ...any) *KV_BatchCreate_Call {
	return &KV_BatchCreate_Call{Call: _e.mock.On("BatchCreate",
		append([]any{ctx, data}, opts...)...)}
}

func (_c *KV_BatchCreate_Call) Run(run func(ctx context.Context, data map[string]string, opts ...clientv3.OpOption)) *KV_BatchCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]string
		if args[1] != nil {
			arg1 = args[1].(map[string]string)
		}
		var arg2 []clientv3.OpOption
		var variadicArgs []clientv3.OpOption
		if len(args) > 2 {
			variadicArgs = args[2].([]clientv3.OpOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *KV_BatchCreate_Call) Return(txnResponse *clientv3.TxnResponse, err error) *KV_BatchCreate_Call {
	_c.Call.Return(txnResponse, err)
	return _c
}

func (_c *KV_BatchCreate_Call) RunAndReturn(run func(ctx context.Context, data map[string]string, opts ...clientv3.OpOption) (*clientv3.TxnResponse, error)) *KV_BatchCreate_Call {
	_c.Call.Return(run)
	return _c
}

// BatchCreateAndDecr provides a mock function for the type KV
func (_mock *KV) BatchCreateAndDecr(ctx context.Context, data map[string]string, decrKey string) error {
	ret := _mock.Called(ctx, data, decrKey)

	if len(ret) == 0 {
		panic("no return value specified for BatchCreateAndDecr")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]string, string) error); ok {
		r0 = returnFunc(ctx, data, decrKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// KV_BatchCreateAndDecr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchCreateAndDecr'
type KV_BatchCreateAndDecr_Call struct {
	*mock.Call
}

// BatchCreateAndDecr is a helper method to define mock.On call
//   - ctx context.Context
//   - data map[string]string
//   - decrKey string
func (_e *KV_Expecter) BatchCreateAndDecr(ctx any, data any, decrKey any) *KV_BatchCreateAndDecr_Call {
	return &KV_BatchCreateAndDecr_Call{Call: _e.mock.On("BatchCreateAndDecr", ctx, data, decrKey)}
}

func (_c *KV_BatchCreateAndDecr_Call) Run(run func(ctx context.Context, data map[string]string, decrKey string)) *KV_BatchCreateAndDecr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]string
		if args[1] != nil {
			arg1 = args[1].(map[string]string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *KV_BatchCreateAndDecr_Call) Return(err error) *KV_BatchCreateAndDecr_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *KV_BatchCreateAndDecr_Call) RunAndReturn(run func(ctx context.Context, data map[string]string, decrKey string) error) *KV_BatchCreateAndDecr_Call {
	_c.Call.Return(run)
	return _c
}

// BatchDelete provides a mock function for the type KV
func (_mock *KV) BatchDelete(ctx context.Context, keys []string, opts ...clientv3.OpOption) (*clientv3.TxnResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, keys, opts)
	} else {
		tmpRet = _mock.Called(ctx, keys)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for BatchDelete")
	}

	var r0 *clientv3.TxnResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, ...clientv3.OpOption) (*clientv3.TxnResponse, error)); ok {
		return returnFunc(ctx, keys, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, ...clientv3.OpOption) *clientv3.TxnResponse); ok {
		r0 = returnFunc(ctx, keys, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clientv3.TxnResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, ...clientv3.OpOption) error); ok {
		r1 = returnFunc(ctx, keys, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KV_BatchDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchDelete'
type KV_BatchDelete_Call struct {
	*mock.Call
}

// BatchDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - keys []string
//   - opts ...clientv3.OpOption
func (_e *KV_Expecter) BatchDelete(ctx any, keys any, opts ...any) *KV_BatchDelete_Call {
	return &KV_BatchDelete_Call{Call: _e.mock.On("BatchDelete",
		append([]any{ctx, keys}, opts...)...)}
}

func (_c *KV_BatchDelete_Call) Run(run func(ctx context.Context, keys []string, opts ...clientv3.OpOption)) *KV_BatchDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 []clientv3.OpOption
		var variadicArgs []clientv3.OpOption
		if len(args) > 2 {
			variadicArgs = args[2].([]clientv3.OpOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *KV_BatchDelete_Call) Return(txnResponse *clientv3.TxnResponse, err error) *KV_BatchDelete_Call {
	_c.Call.Return(txnResponse, err)
	return _c
}

func (_c *KV_BatchDelete_Call) RunAndReturn(run func(ctx context.Context, keys []string, opts ...clientv3.OpOption) (*clientv3.TxnResponse, error)) *KV_BatchDelete_Call {
	_c.Call.Return(run)
	return _c
}

// BatchPut provides a mock function for the type KV
func (_mock *KV) BatchPut(ctx context.Context, data map[string]string, opts ...clientv3.OpOption) (*clientv3.TxnResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, data, opts)
	} else {
		tmpRet = _mock.Called(ctx, data)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for BatchPut")
	}

	var r0 *clientv3.TxnResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]string, ...clientv3.OpOption) (*clientv3.TxnResponse, error)); ok {
		return returnFunc(ctx, data, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]string, ...clientv3.OpOption) *clientv3.TxnResponse); ok {
		r0 = returnFunc(ctx, data, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clientv3.TxnResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, map[string]string, ...clientv3.OpOption) error); ok {
		r1 = returnFunc(ctx, data, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KV_BatchPut_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchPut'
type KV_BatchPut_Call struct {
	*mock.Call
}

// BatchPut is a helper method to define mock.On call
//   - ctx context.Context
//   - data map[string]string
//   - opts ...clientv3.OpOption
func (_e *KV_Expecter) BatchPut(ctx any, data any, opts ...any) *KV_BatchPut_Call {
	return &KV_BatchPut_Call{Call: _e.mock.On("BatchPut",
		append([]any{ctx, data}, opts...)...)}
}

func (_c *KV_BatchPut_Call) Run(run func(ctx context.Context, data map[string]string, opts ...clientv3.OpOption)) *KV_BatchPut_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]string
		if args[1] != nil {
			arg1 = args[1].(map[string]string)
		}
		var arg2 []clientv3.OpOption
		var variadicArgs []clientv3.OpOption
		if len(args) > 2 {
			variadicArgs = args[2].([]clientv3.OpOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *KV_BatchPut_Call) Return(txnResponse *clientv3.TxnResponse, err error) *KV_BatchPut_Call {
	_c.Call.Return(txnResponse, err)
	return _c
}

func (_c *KV_BatchPut_Call) RunAndReturn(run func(ctx context.Context, data map[string]string, opts ...clientv3.OpOption) (*clientv3.TxnResponse, error)) *KV_BatchPut_Call {
	_c.Call.Return(run)
	return _c
}

// BatchUpdate provides a mock function for the type KV
func (_mock *KV) BatchUpdate(ctx context.Context, data map[string]string, opts ...clientv3.OpOption) (*clientv3.TxnResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, data, opts)
	} else {
		tmpRet = _mock.Called(ctx, data)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for BatchUpdate")
	}

	var r0 *clientv3.TxnResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]string, ...clientv3.OpOption) (*clientv3.TxnResponse, error)); ok {
		return returnFunc(ctx, data, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]string, ...clientv3.OpOption) *clientv3.TxnResponse); ok {
		r0 = returnFunc(ctx, data, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clientv3.TxnResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, map[string]string, ...clientv3.OpOption) error); ok {
		r1 = returnFunc(ctx, data, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KV_BatchUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchUpdate'
type KV_BatchUpdate_Call struct {
	*mock.Call
}

// BatchUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - data map[string]string
//   - opts ...clientv3.OpOption
func (_e *KV_Expecter) BatchUpdate(ctx any, data any, opts ...any) *KV_BatchUpdate_Call {
	return &KV_BatchUpdate_Call{Call: _e.mock.On("BatchUpdate",
		append([]any{ctx, data}, opts...)...)}
}

func (_c *KV_BatchUpdate_Call) Run(run func(ctx context.Context, data map[string]string, opts ...clientv3.OpOption)) *KV_BatchUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]string
		if args[1] != nil {
			arg1 = args[1].(map[string]string)
		}
		var arg2 []clientv3.OpOption
		var variadicArgs []clientv3.OpOption
		if len(args) > 2 {
			variadicArgs = args[2].([]clientv3.OpOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *KV_BatchUpdate_Call) Return(txnResponse *clientv3.TxnResponse, err error) *KV_BatchUpdate_Call {
	_c.Call.Return(txnResponse, err)
	return _c
}

func (_c *KV_BatchUpdate_Call) RunAndReturn(run func(ctx context.Context, data map[string]string, opts ...clientv3.OpOption) (*clientv3.TxnResponse, error)) *KV_BatchUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// BindStatus provides a mock function for the type KV
func (_mock *KV) BindStatus(ctx context.Context, entityKey string, statusKey string, statusValue string, ttl int64) error {
	ret := _mock.Called(ctx, entityKey, statusKey, statusValue, ttl)

	if len(ret) == 0 {
		panic("no return value specified for BindStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, int64) error); ok {
		r0 = returnFunc(ctx, entityKey, statusKey, statusValue, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// KV_BindStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BindStatus'
type KV_BindStatus_Call struct {
	*mock.Call
}

// BindStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - entityKey string
//   - statusKey string
//   - statusValue string
//   - ttl int64
func (_e *KV_Expecter) BindStatus(ctx any, entityKey any, statusKey any, statusValue any, ttl any) *KV_BindStatus_Call {
	return &KV_BindStatus_Call{Call: _e.mock.On("BindStatus", ctx, entityKey, statusKey, statusValue, ttl)}
}

func (_c *KV_BindStatus_Call) Run(run func(ctx context.Context, entityKey string, statusKey string, statusValue string, ttl int64)) *KV_BindStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *KV_BindStatus_Call) Return(err error) *KV_BindStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *KV_BindStatus_Call) RunAndReturn(run func(ctx context.Context, entityKey string, statusKey string, statusValue string, ttl int64) error) *KV_BindStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type KV
func (_mock *KV) Create(ctx context.Context, key string, val string, opts ...clientv3.OpOption) (*clientv3.TxnResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, key, val, opts)
	} else {
		tmpRet = _mock.Called(ctx, key, val)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *clientv3.TxnResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...clientv3.OpOption) (*clientv3.TxnResponse, error)); ok {
		return returnFunc(ctx, key, val, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...clientv3.OpOption) *clientv3.TxnResponse); ok {
		r0 = returnFunc(ctx, key, val, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clientv3.TxnResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, ...clientv3.OpOption) error); ok {
		r1 = returnFunc(ctx, key, val, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KV_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type KV_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - val string
//   - opts ...clientv3.OpOption
func (_e *KV_Expecter) Create(ctx any, key any, val any, opts ...any) *KV_Create_Call {
	return &KV_Create_Call{Call: _e.mock.On("Create",
		append([]any{ctx, key, val}, opts...)...)}
}

func (_c *KV_Create_Call) Run(run func(ctx context.Context, key string, val string, opts ...clientv3.OpOption)) *KV_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []clientv3.OpOption
		var variadicArgs []clientv3.OpOption
		if len(args) > 3 {
			variadicArgs = args[3].([]clientv3.OpOption)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *KV_Create_Call) Return(txnResponse *clientv3.TxnResponse, err error) *KV_Create_Call {
	_c.Call.Return(txnResponse, err)
	return _c
}

func (_c *KV_Create_Call) RunAndReturn(run func(ctx context.Context, key string, val string, opts ...clientv3.OpOption) (*clientv3.TxnResponse, error)) *KV_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateLock provides a mock function for the type KV
func (_mock *KV) CreateLock(key string, ttl time.Duration) (lock.DistributedLock, error) {
	ret := _mock.Called(key, ttl)

	if len(ret) == 0 {
		panic("no return value specified for CreateLock")
	}

	var r0 lock.DistributedLock
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, time.Duration) (lock.DistributedLock, error)); ok {
		return returnFunc(key, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(string, time.Duration) lock.DistributedLock); ok {
		r0 = returnFunc(key, ttl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(lock.DistributedLock)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, time.Duration) error); ok {
		r1 = returnFunc(key, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KV_CreateLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLock'
type KV_CreateLock_Call struct {
	*mock.Call
}

// CreateLock is a helper method to define mock.On call
//   - key string
//   - ttl time.Duration
func (_e *KV_Expecter) CreateLock(key any, ttl any) *KV_CreateLock_Call {
	return &KV_CreateLock_Call{Call: _e.mock.On("CreateLock", key, ttl)}
}

func (_c *KV_CreateLock_Call) Run(run func(key string, ttl time.Duration)) *KV_CreateLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *KV_CreateLock_Call) Return(distributedLock lock.DistributedLock, err error) *KV_CreateLock_Call {
	_c.Call.Return(distributedLock, err)
	return _c
}

func (_c *KV_CreateLock_Call) RunAndReturn(run func(key string, ttl time.Duration) (lock.DistributedLock, error)) *KV_CreateLock_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type KV
func (_mock *KV) Delete(ctx context.Context, key string, opts ...clientv3.OpOption) (*clientv3.DeleteResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, key, opts)
	} else {
		tmpRet = _mock.Called(ctx, key)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *clientv3.DeleteResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...clientv3.OpOption) (*clientv3.DeleteResponse, error)); ok {
		return returnFunc(ctx, key, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...clientv3.OpOption) *clientv3.DeleteResponse); ok {
		r0 = returnFunc(ctx, key, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clientv3.DeleteResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...clientv3.OpOption) error); ok {
		r1 = returnFunc(ctx, key, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KV_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type KV_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - opts ...clientv3.OpOption
func (_e *KV_Expecter) Delete(ctx any, key any, opts ...any) *KV_Delete_Call {
	return &KV_Delete_Call{Call: _e.mock.On("Delete",
		append([]any{ctx, key}, opts...)...)}
}

func (_c *KV_Delete_Call) Run(run func(ctx context.Context, key string, opts ...clientv3.OpOption)) *KV_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []clientv3.OpOption
		var variadicArgs []clientv3.OpOption
		if len(args) > 2 {
			variadicArgs = args[2].([]clientv3.OpOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *KV_Delete_Call) Return(deleteResponse *clientv3.DeleteResponse, err error) *KV_Delete_Call {
	_c.Call.Return(deleteResponse, err)
	return _c
}

func (_c *KV_Delete_Call) RunAndReturn(run func(ctx context.Context, key string, opts ...clientv3.OpOption) (*clientv3.DeleteResponse, error)) *KV_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type KV
func (_mock *KV) Get(ctx context.Context, key string, opts ...clientv3.OpOption) (*clientv3.GetResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, key, opts)
	} else {
		tmpRet = _mock.Called(ctx, key)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *clientv3.GetResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...clientv3.OpOption) (*clientv3.GetResponse, error)); ok {
		return returnFunc(ctx, key, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...clientv3.OpOption) *clientv3.GetResponse); ok {
		r0 = returnFunc(ctx, key, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clientv3.GetResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...clientv3.OpOption) error); ok {
		r1 = returnFunc(ctx, key, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KV_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type KV_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - opts ...clientv3.OpOption
func (_e *KV_Expecter) Get(ctx any, key any, opts ...any) *KV_Get_Call {
	return &KV_Get_Call{Call: _e.mock.On("Get",
		append([]any{ctx, key}, opts...)...)}
}

func (_c *KV_Get_Call) Run(run func(ctx context.Context, key string, opts ...clientv3.OpOption)) *KV_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []clientv3.OpOption
		var variadicArgs []clientv3.OpOption
		if len(args) > 2 {
			variadicArgs = args[2].([]clientv3.OpOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *KV_Get_Call) Return(getResponse *clientv3.GetResponse, err error) *KV_Get_Call {
	_c.Call.Return(getResponse, err)
	return _c
}

func (_c *KV_Get_Call) RunAndReturn(run func(ctx context.Context, key string, opts ...clientv3.OpOption) (*clientv3.GetResponse, error)) *KV_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetMulti provides a mock function for the type KV
func (_mock *KV) GetMulti(ctx context.Context, keys []string, opts ...clientv3.OpOption) ([]*mvccpb.KeyValue, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, keys, opts)
	} else {
		tmpRet = _mock.Called(ctx, keys)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetMulti")
	}

	var r0 []*mvccpb.KeyValue
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, ...clientv3.OpOption) ([]*mvccpb.KeyValue, error)); ok {
		return returnFunc(ctx, keys, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, ...clientv3.OpOption) []*mvccpb.KeyValue); ok {
		r0 = returnFunc(ctx, keys, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*mvccpb.KeyValue)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, ...clientv3.OpOption) error); ok {
		r1 = returnFunc(ctx, keys, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KV_GetMulti_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMulti'
type KV_GetMulti_Call struct {
	*mock.Call
}

// GetMulti is a helper method to define mock.On call
//   - ctx context.Context
//   - keys []string
//   - opts ...clientv3.OpOption
func (_e *KV_Expecter) GetMulti(ctx any, keys any, opts ...any) *KV_GetMulti_Call {
	return &KV_GetMulti_Call{Call: _e.mock.On("GetMulti",
		append([]any{ctx, keys}, opts...)...)}
}

func (_c *KV_GetMulti_Call) Run(run func(ctx context.Context, keys []string, opts ...clientv3.OpOption)) *KV_GetMulti_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 []clientv3.OpOption
		var variadicArgs []clientv3.OpOption
		if len(args) > 2 {
			variadicArgs = args[2].([]clientv3.OpOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *KV_GetMulti_Call) Return(kvs []*mvccpb.KeyValue, err error) *KV_GetMulti_Call {
	_c.Call.Return(kvs, err)
	return _c
}

func (_c *KV_GetMulti_Call) RunAndReturn(run func(ctx context.Context, keys []string, opts ...clientv3.OpOption) ([]*mvccpb.KeyValue, error)) *KV_GetMulti_Call {
	_c.Call.Return(run)
	return _c
}

// GetOne provides a mock function for the type KV
func (_mock *KV) GetOne(ctx context.Context, key string, opts ...clientv3.OpOption) (*mvccpb.KeyValue, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, key, opts)
	} else {
		tmpRet = _mock.Called(ctx, key)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetOne")
	}

	var r0 *mvccpb.KeyValue
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...clientv3.OpOption) (*mvccpb.KeyValue, error)); ok {
		return returnFunc(ctx, key, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...clientv3.OpOption) *mvccpb.KeyValue); ok {
		r0 = returnFunc(ctx, key, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mvccpb.KeyValue)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...clientv3.OpOption) error); ok {
		r1 = returnFunc(ctx, key, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KV_GetOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOne'
type KV_GetOne_Call struct {
	*mock.Call
}

// GetOne is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - opts ...clientv3.OpOption
func (_e *KV_Expecter) GetOne(ctx any, key any, opts ...any) *KV_GetOne_Call {
	return &KV_GetOne_Call{Call: _e.mock.On("GetOne",
		append([]any{ctx, key}, opts...)...)}
}

func (_c *KV_GetOne_Call) Run(run func(ctx context.Context, key string, opts ...clientv3.OpOption)) *KV_GetOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []clientv3.OpOption
		var variadicArgs []clientv3.OpOption
		if len(args) > 2 {
			variadicArgs = args[2].([]clientv3.OpOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *KV_GetOne_Call) Return(keyValue *mvccpb.KeyValue, err error) *KV_GetOne_Call {
	_c.Call.Return(keyValue, err)
	return _c
}

func (_c *KV_GetOne_Call) RunAndReturn(run func(ctx context.Context, key string, opts ...clientv3.OpOption) (*mvccpb.KeyValue, error)) *KV_GetOne_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type KV
func (_mock *KV) Put(ctx context.Context, key string, val string, opts ...clientv3.OpOption) (*clientv3.PutResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, key, val, opts)
	} else {
		tmpRet = _mock.Called(ctx, key, val)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 *clientv3.PutResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...clientv3.OpOption) (*clientv3.PutResponse, error)); ok {
		return returnFunc(ctx, key, val, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...clientv3.OpOption) *clientv3.PutResponse); ok {
		r0 = returnFunc(ctx, key, val, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clientv3.PutResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, ...clientv3.OpOption) error); ok {
		r1 = returnFunc(ctx, key, val, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KV_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type KV_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - val string
//   - opts ...clientv3.OpOption
func (_e *KV_Expecter) Put(ctx any, key any, val any, opts ...any) *KV_Put_Call {
	return &KV_Put_Call{Call: _e.mock.On("Put",
		append([]any{ctx, key, val}, opts...)...)}
}

func (_c *KV_Put_Call) Run(run func(ctx context.Context, key string, val string, opts ...clientv3.OpOption)) *KV_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []clientv3.OpOption
		var variadicArgs []clientv3.OpOption
		if len(args) > 3 {
			variadicArgs = args[3].([]clientv3.OpOption)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *KV_Put_Call) Return(putResponse *clientv3.PutResponse, err error) *KV_Put_Call {
	_c.Call.Return(putResponse, err)
	return _c
}

func (_c *KV_Put_Call) RunAndReturn(run func(ctx context.Context, key string, val string, opts ...clientv3.OpOption) (*clientv3.PutResponse, error)) *KV_Put_Call {
	_c.Call.Return(run)
	return _c
}

// StartEphemeral provides a mock function for the type KV
func (_mock *KV) StartEphemeral(ctx context.Context, path string, heartbeat time.Duration) (<-chan struct{}, func(), error) {
	ret := _mock.Called(ctx, path, heartbeat)

	if len(ret) == 0 {
		panic("no return value specified for StartEphemeral")
	}

	var r0 <-chan struct{}
	var r1 func()
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) (<-chan struct{}, func(), error)); ok {
		return returnFunc(ctx, path, heartbeat)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) <-chan struct{}); ok {
		r0 = returnFunc(ctx, path, heartbeat)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Duration) func()); ok {
		r1 = returnFunc(ctx, path, heartbeat)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(func())
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, time.Duration) error); ok {
		r2 = returnFunc(ctx, path, heartbeat)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// KV_StartEphemeral_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartEphemeral'
type KV_StartEphemeral_Call struct {
	*mock.Call
}

// StartEphemeral is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - heartbeat time.Duration
func (_e *KV_Expecter) StartEphemeral(ctx any, path any, heartbeat any) *KV_StartEphemeral_Call {
	return &KV_StartEphemeral_Call{Call: _e.mock.On("StartEphemeral", ctx, path, heartbeat)}
}

func (_c *KV_StartEphemeral_Call) Run(run func(ctx context.Context, path string, heartbeat time.Duration)) *KV_StartEphemeral_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *KV_StartEphemeral_Call) Return(valCh <-chan struct{}, fn func(), err error) *KV_StartEphemeral_Call {
	_c.Call.Return(valCh, fn, err)
	return _c
}

func (_c *KV_StartEphemeral_Call) RunAndReturn(run func(ctx context.Context, path string, heartbeat time.Duration) (<-chan struct{}, func(), error)) *KV_StartEphemeral_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function for the type KV
func (_mock *KV) Watch(ctx context.Context, key string, opts ...clientv3.OpOption) clientv3.WatchChan {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, key, opts)
	} else {
		tmpRet = _mock.Called(ctx, key)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 clientv3.WatchChan
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...clientv3.OpOption) clientv3.WatchChan); ok {
		r0 = returnFunc(ctx, key, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(clientv3.WatchChan)
		}
	}
	return r0
}

// KV_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type KV_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - opts ...clientv3.OpOption
func (_e *KV_Expecter) Watch(ctx any, key any, opts ...any) *KV_Watch_Call {
	return &KV_Watch_Call{Call: _e.mock.On("Watch",
		append([]any{ctx, key}, opts...)...)}
}

func (_c *KV_Watch_Call) Run(run func(ctx context.Context, key string, opts ...clientv3.OpOption)) *KV_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []clientv3.OpOption
		var variadicArgs []clientv3.OpOption
		if len(args) > 2 {
			variadicArgs = args[2].([]clientv3.OpOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *KV_Watch_Call) Return(watchChan clientv3.WatchChan) *KV_Watch_Call {
	_c.Call.Return(watchChan)
	return _c
}

func (_c *KV_Watch_Call) RunAndReturn(run func(ctx context.Context, key string, opts ...clientv3.OpOption) clientv3.WatchChan) *KV_Watch_Call {
	_c.Call.Return(run)
	return _c
}
