// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	context "context"

	wal "github.com/projecteru2/core/wal"
	mock "github.com/stretchr/testify/mock"
)

// WAL is an autogenerated mock type for the WAL type
type WAL struct {
	mock.Mock
}

// Log provides a mock function with given fields: _a0, _a1, _a2
func (_m *WAL) Log(_a0 context.Context, _a1 string, _a2 interface{}) (wal.Commit, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 wal.Commit
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) wal.Commit); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(wal.Commit)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, interface{}) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Recover provides a mock function with given fields: _a0
func (_m *WAL) Recover(_a0 context.Context) {
	_m.Called(_a0)
}

// Register provides a mock function with given fields: _a0
func (_m *WAL) Register(_a0 wal.EventHandler) {
	_m.Called(_a0)
}
