name: test

on:
  push:
    tags:
      - '!v*'
    branches:
      - '*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'

      - name: Download dependencies
        run: go mod download

      - name: Vet
        run: go vet ./...

      - name: Test with coverage
        run: go test -race -timeout 600s -count=1 -cover -coverprofile=coverage.out ./...

      - name: Upload coverage artifact
        continue-on-error: true
        uses: actions/upload-artifact@v7
        with:
          name: coverage
          path: coverage.out
          retention-days: 7

      - name: Build binary
        run: CGO_ENABLED=0 go build -o eru-core .
